// AUTOGENERATED from MACROS IM8 Affiliates.xlsx
// on 2026-05-15. Source of truth lives in that file — re-run
// /Users/cherie/Desktop/extract-affiliate-macros.py when Kendra updates it.
// Do not hand-edit; changes will be lost on regeneration.

export const AFFILIATES_DATA = {
  "principles": [
    {
      "title": "Protect Authentic Voice",
      "body": "Every response builds trust, not just closes a ticket. Affiliates should feel supported, not managed. Use the full macro — don't truncate or improvise."
    },
    {
      "title": "Clarity Over Speed",
      "body": "A clear answer the first time beats a fast reply that generates two follow-ups. Aim to resolve within 2 days; aim to resolve fully in one reply."
    },
    {
      "title": "Commission-First Framing",
      "body": "Always anchor value in earnings and performance rewards, not free product. Product is a perk, not the program. When in doubt, default to the activation reward."
    },
    {
      "title": "Know What You Can Commit To",
      "body": "Confirm what policy covers — do not promise anything outside it. Seeding, rewards, and paid partnerships each have their own rules. If it's not in the SOP, flag it."
    },
    {
      "title": "Escalate Early, Not Late",
      "body": "Flag paid partnership requests, legacy reward claims, and anything involving disputed amounts to the manager before responding. A held ticket is better than a wrong commitment."
    }
  ],
  "overview": [
    {
      "heading": "IM8 AFFILIATE PROGRAM — AGENT OVERVIEW",
      "items": []
    },
    {
      "heading": "Read this before handling any affiliate email. It gives you the background to understand what affiliates expect and why the macros are written the way they are.",
      "items": []
    },
    {
      "heading": "WHAT IS THE IM8 AFFILIATE PROGRAM?",
      "items": [
        {
          "label": "What it is",
          "body": "A commission-based referral program. Affiliates share their unique discount code or referral link. When someone buys using either, the affiliate earns 10% of the sale. The customer gets 10% off. That's the deal."
        },
        {
          "label": "What it is NOT",
          "body": "A gifting program. Affiliates don't automatically receive free product for joining. Free product is earned through the activation reward and sales milestones — not given at signup. This is the most common point of confusion."
        },
        {
          "label": "Referral link format",
          "body": "im8health.com/discount/[CODE]"
        },
        {
          "label": "Platform",
          "body": "Social Snowball (SS). Affiliates log in here to access their link, code, sales data, and payout setup. Migrated from TUNE Pay on April 14, 2026.\n\nSign-up: https://im8health.socialsnowball.io/signup/bcdd67d9-5310-490b-8b05-e13e273af2e5\nLogin: https://affiliates.socialsnowball.io/auth/affiliate/login"
        },
        {
          "label": "Program Information",
          "body": "SOCIAL SNOWBALL — PROGRAMS OVERVIEW\nThese are the commission structures currently active in SS. CS needs to understand which program an affiliate is on before answering any payout or commission question.\n\n10% Commission, 1st Order \nThe standard program. Anyone joining through the ambassador signup link is routed here automatically. Affiliate earns 10% commission on the customer's first order only. Customer gets 10% off.\n\n15% Commission, 1st Order\nSame structure as above but with a higher commission rate. These are affiliates migrated across from TUNE / HasOffers when we moved to Social Snowball on April 14, 2026. They were grandfathered in at the higher rate. Customer still gets 10% off.\n\n[Outreach] 10% Commission, 1st Order \nSame commission structure as the standard 10% program. These affiliates were brought in directly through outreach by our internal team rather than through the standard signup link. Functionally identical to the standard program for payout purposes.\n\nDisabled\nAffiliates who previously earned commission but have been moved to 0% commission. Their discount code still works and customers still get 10% off — but the affiliate earns nothing. Do not discuss commission with these affiliates without flagging to manager first.\n\n$20 First Order \nDr. James only. Fixed $20 flat commission on the first order rather than a percentage. Do not reference this program to any other affiliate — it is a bespoke arrangement.\n\n50% Commission, 1st Order \nVVIP ambassador only. 50% commission on their first order. Bespoke arrangement — do not reference or offer this rate to any other affiliate under any circumstances. \n\nKey rule for CS: If an affiliate questions their commission rate or says it doesn't match what they expected — check which program they're on in SS admin before replying. Never assume they're on the standard 10% program."
        },
        {
          "label": "Support — Email & Discord",
          "body": "Discord (discord.com/invite/tpzwzpWbvs) — direct affiliates here first for quick questions, community support, and general program queries. Fastest response.\n\nEmail (affiliates@im8health.com) — for formal inquiries, account issues, reward claims, and anything that needs a paper trail."
        }
      ]
    },
    {
      "heading": "HOW DO AFFILIATES JOIN?",
      "items": [
        {
          "label": "Signup link",
          "body": "Affiliates apply via the Social Snowball signup link. Approval is automatic and they receive a confirmation email with instructions to set up their password, their referral link and discount code.\n\nThere are two ways that they find our program: \n1. Through our website & footer: https://im8health.com/pages/im8-ambassador-program\n2. Through the Brand & Partnerships Typeform link (either shared by CS or within our FAQs) > \"I want to earn by recommending IM8 through my circle of influence\": https://form.typeform.com/to/iclm3vWt\n3. Through CS sending them the sign up page directly: https://im8health.socialsnowball.io/signup/bcdd67d9-5310-490b-8b05-e13e273af2e5"
        },
        {
          "label": "Approval time",
          "body": "Immediately."
        },
        {
          "label": "What they get on activation",
          "body": "1. Referral link: im8health.com/discount/[THEIR CODE]\n2. Discount code: [THEIR CODE] (audience uses this at checkout)\n3. Access to set up their Social Snowball password\n3. Access to Social Snowball dashboard (track clicks, sales, earnings, set up payout)\n4. Access to ambassador hub: im8ambassador.netlify.app\n5. Invite to affiliate Discord community: https://discord.com/invite/tpzwzpWbvs"
        }
      ]
    },
    {
      "heading": "HOW AFFILIATES EARN & GET PAID",
      "items": [
        {
          "label": "Commission",
          "body": "10% on every confirmed sale made through their discount code or referral link."
        },
        {
          "label": "Payout schedule",
          "body": "Monthly — end of each calendar month, usually within two weeks."
        },
        {
          "label": "Commission hold",
          "body": "30 days from the date of sale. Covers the refund window.\n\nTimeline:\n→ Sale on January 10\n→ Hold clears February 10\n→ Included in February month-end payout, processed early March\n\nSales in Month 1 → cleared Month 2 → paid Month 3.\n\nNew affiliates: first payout takes longer than expected. That's the hold window — not a problem."
        },
        {
          "label": "Minimum threshold",
          "body": "$100 USD. Balances under $100 roll over. No expiry."
        },
        {
          "label": "Payout setup",
          "body": "Two-step process in SS. Step 1: Edit recipient information → Save. Step 2: Payout Methods tab → add PayPal or bank."
        },
        {
          "label": "Currency",
          "body": "USD. Conversion handled by the affiliate's own payment provider."
        }
      ]
    },
    {
      "heading": "LIFETIME PERFORMANCE REWARD TIERS",
      "items": [
        {
          "label": "Activation reward\n(Discord + Strava + post in both)",
          "body": "Join Discord + Strava + post in both → 7-day supply + Red Signature Cup\n\nWhat counts as a post:\n• Discord: intro post in the IM8 Ambassador server\n• Strava: a workout log or post in the IM8 Health club\n\nActivation form (submit screenshots): https://forms.gle/hfNbyjGx1DWYsmvK6\nDiscord: https://discord.com/invite/tpzwzpWbvs\nStrava: https://strava.app.link/u94yPNhyb2b\n\nVerification: internal team checks submissions. Reward ships once verified."
        },
        {
          "label": "3rd lifetime sale",
          "body": "3x 7-ct sample packs + Silver frother.\nShipping form: https://forms.gle/3TKTCjTg8e3bb7ScA\n\nTurns one affiliate into 5 potential customers. The frother is visual — they'll post it."
        },
        {
          "label": "10th lifetime sale",
          "body": "30-day supply + hat.\nItem: TBD — pending confirmation.\n\nBy sale 10 they've generated real revenue. The reward should feel like a promotion."
        }
      ]
    },
    {
      "heading": "MONTHLY PERFORMANCE REWARD TIERS",
      "items": [
        {
          "label": "Tier 1 — 5 sales/month",
          "body": "Free monthly supply of Daily Ultimate Essentials (affiliate's choice of flavour). Affiliate submits a shipping/reward form to claim."
        },
        {
          "label": "Tier 2 — 15 sales/month",
          "body": "Free monthly Essentials + Longevity supply."
        },
        {
          "label": "Tier 3 — 30 sales/month",
          "body": "Full Beckham Stack quarterly (3-month supply affiliates flavour of choice)."
        },
        {
          "label": "How to process",
          "body": "When an affiliate says they've hit a tier, congratulate them, confirm the tier, and send the reward/shipping form link. Do not process manually — the form handles it."
        }
      ]
    },
    {
      "heading": "WHAT CS HANDLES vs WHAT TO ESCALATE",
      "items": [
        {
          "label": "CS handles independently",
          "body": "• All payout and commission questions\n• SS technical issues (login, payout setup, broken links, dashboard errors)\n• Onboarding (getting started, find my link/code, code changes, approval status)\n• Performance tier reward processing\n• Creator Challenge prize claims (send vendor form)\n• FTC/disclosure questions"
        },
        {
          "label": "Flag to manager BEFORE replying",
          "body": "• Paid partnership / sponsored content requests\n• Talent manager or agency inquiries\n• Retail / wholesale / reseller inquiries\n• Sponsorship requests\n• Legacy reward claims (old program, disputed amounts)\n• Any legal language or chargeback threats\n• Anything not covered by the SOP"
        },
        {
          "label": "ESCALATION CHANNEL",
          "body": "Slack Channel: #im8-affiliate-faqs"
        },
        {
          "label": "Rule",
          "body": "A held ticket flagged to the manager is always better than a wrong commitment sent to an affiliate. When in doubt — flag first."
        }
      ]
    }
  ],
  "decisions": [
    {
      "num": "1",
      "trigger": "How does this work / how do I start / just signed up / welcome",
      "tag": "onboarding - getting started",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "Send getting-started breakdown: SS login (https://affiliates.socialsnowball.io/auth/affiliate/login), referral link format (im8health.com/discount/[CODE]), \nambassador hub (https://im8ambassador.netlify.app/), \nDiscord (https://discord.com/invite/tpzwzpWbvs), \nStrava (https://strava.app.link/u94yPNhyb2b). \nExplain the activation path: join Discord + Strava → unlock activation reward → 1st sale → free product starts.",
      "approachBullets": [
        "Walk them through getting started: SS login, referral link, discount code",
        "Send the activation path: Discord + Strava + post in both → 7-day supply",
        "Point them to the ambassador hub for content resources"
      ],
      "macroSheet": "MACROS — Onboarding"
    },
    {
      "num": "2",
      "trigger": "Where is my link / where is my code / can't find my dashboard",
      "tag": "onboarding - find link/code",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "Log into SS at https://affiliates.socialsnowball.io/auth/affiliate/login. Referral link = im8health.com/discount/[CODE]. Discount code shown directly below the link on the home screen.",
      "approachBullets": [
        "Login at SS dashboard: https://affiliates.socialsnowball.io/auth/affiliate/login",
        "Referral link format: im8health.com/discount/[CODE]",
        "Discount code is shown directly below the link on the home screen"
      ],
      "macroSheet": "MACROS — Onboarding"
    },
    {
      "num": "3",
      "trigger": "Can I get free samples / I want to try it / need product to promote / do I need to buy product",
      "tag": "seeding - trial request",
      "track": "inbound affiliates",
      "escalate": "No",
      "seeding": "No — walk through activation path",
      "approach": "Walk through the activation path: (1) Join Discord (https://discord.com/invite/tpzwzpWbvs) + Strava (https://strava.app.link/u94yPNhyb2b) and post in both. (2) Submit screenshots via activation form: https://forms.gle/hfNbyjGx1DWYsmvK6. (3) Verified → 7-day supply + Red Cup ships. This unlocks the activation reward too.",
      "approachBullets": [
        "Join Discord + Strava and post intro in both",
        "Submit screenshots via the activation form: https://forms.gle/hfNbyjGx1DWYsmvK6",
        "Once verified, a 7-day supply + Red Cup ships"
      ],
      "macroSheet": "MACROS — Product & Seeding"
    },
    {
      "num": "4",
      "trigger": "I never received products / thought this was a product program / expected free product",
      "tag": "seeding - program clarity",
      "track": "inbound affiliates",
      "escalate": "No",
      "seeding": "No — walk through activation path",
      "approach": "Clarify: commission-based, not a gifting program. Free product is earned. Path: (1) Join Discord (https://discord.com/invite/tpzwzpWbvs) + Strava (https://strava.app.link/u94yPNhyb2b), post in both. (2) Submit screenshots: https://forms.gle/hfNbyjGx1DWYsmvK6. (3) Verified → 7-day supply + Red Cup ships. After that: 3rd lifetime sale → sample packs + frother. 10th lifetime sale → 30-day supply + merch.",
      "approachBullets": [
        "Clarify: commission-based program, not a gifting program",
        "Free product is earned, not given at signup",
        "Path to free product: Join Discord + Strava → submit screenshots → 7-day supply ships"
      ],
      "macroSheet": "MACROS — Product & Seeding"
    },
    {
      "num": "5",
      "trigger": "Payout / minimum / when do I get paid / withdrawal / how does payment work",
      "tag": "payouts - threshold",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "$100 USD minimum, monthly (end of calendar month), 30-day hold. Example: January sale → February hold clears → March payout. Payout method must be set up in SS: https://affiliates.socialsnowball.io/auth/affiliate/login",
      "approachBullets": [
        "Pay schedule: monthly, end of each calendar month",
        "Minimum payout: $100 USD (anything under rolls over)",
        "30-day hold from sale date (refund window)",
        "Timeline example: January sale → February hold clears → March payout",
        "Check: has the affiliate set up a payout method in SS?"
      ],
      "macroSheet": "MACROS — Payouts & Commission"
    },
    {
      "num": "6",
      "trigger": "I haven't been paid / payment is late / is there a payment this month",
      "tag": "payouts - late payment",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "Three checks: (1) Payout method set up in SS? (2) Balance above $100 USD? (3) Sales within 30-day hold? Address whichever applies.",
      "approachBullets": [
        "Is the payout method set up in SS?",
        "Is the balance above $100 USD?",
        "Are the sales within the 30-day hold window?",
        "Address whichever check fails"
      ],
      "macroSheet": "MACROS — Payouts & Commission"
    },
    {
      "num": "7",
      "trigger": "My sales aren't showing / commission missing / I made a sale but it's not in my dashboard",
      "tag": "payouts - missing commission",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "Ask for order number and details. Check pre/post April 14 (TUNE vs SS). Sales only track if the customer used the discount code at checkout.",
      "approachBullets": [
        "Ask for the order number and approximate sale date",
        "Confirm pre/post April 14 — sales before then live in TUNE, after in SS",
        "Sales only track if the customer used the discount code or referral link at checkout"
      ],
      "macroSheet": "MACROS — Payouts & Commission"
    },
    {
      "num": "8",
      "trigger": "TUNE / HasOffers / old link / go2cloud / what happened to my old account",
      "tag": "payouts - TUNE migration",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "April 14 migration to Social Snowball. TUNE balance still paid per TUNE's schedule — nothing lost. All new sales in SS only.",
      "approachBullets": [
        "We migrated from TUNE Pay to Social Snowball on April 14",
        "TUNE balance is still being paid per TUNE's schedule — nothing's lost",
        "All new sales track in Social Snowball only"
      ],
      "macroSheet": "MACROS — Platform & Technical"
    },
    {
      "num": "9",
      "trigger": "Dashboard shows different numbers on TUNE vs SS / numbers don't match",
      "tag": "technical - discrepancy",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "Not linked — expected. TUNE = before April 14. SS = from April 14. Add both for full picture.",
      "approachBullets": [
        "Expected behaviour — TUNE and SS are not linked",
        "TUNE shows pre-April 14 sales",
        "SS shows post-April 14 sales",
        "Tell them to add both together for the full picture"
      ],
      "macroSheet": "MACROS — Platform & Technical"
    },
    {
      "num": "10",
      "trigger": "My link isn't working / referral link broken / old link not tracking",
      "tag": "technical - broken link",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "Old TUNE links (go2cloud.org) inactive. New format: im8health.com/discount/[CODE]. Update bio, stories, saved posts.",
      "approachBullets": [
        "Old TUNE links (go2cloud.org) are no longer active",
        "New link format: im8health.com/discount/[CODE]",
        "Tell them to update bio links, stories, and saved posts"
      ],
      "macroSheet": "MACROS — Platform & Technical"
    },
    {
      "num": "11",
      "trigger": "I can't log in / forgot password / SS login issue",
      "tag": "technical - SS login",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "Reset: go to https://affiliates.socialsnowball.io/auth/affiliate/login, enter signup email, Forgot Password, check spam. Still locked out → ask for signup email and look up account.",
      "approachBullets": [
        "Direct them to https://affiliates.socialsnowball.io/auth/affiliate/login",
        "Enter signup email → click Forgot Password",
        "Check spam if the reset email doesn't land",
        "Still locked out? Ask for signup email and look up the account"
      ],
      "macroSheet": "MACROS — Platform & Technical"
    },
    {
      "num": "12",
      "trigger": "No payout methods / SS payout error / can't add PayPal",
      "tag": "technical - SS payout setup",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "Two separate steps. Step 1: Edit recipient information → Save. Step 2: Payout Methods tab → add PayPal or bank.",
      "approachBullets": [
        "It's a two-step setup — both steps need to be done separately",
        "Step 1: Edit recipient information → Save",
        "Step 2: Payout Methods tab → add PayPal or bank"
      ],
      "macroSheet": "MACROS — Platform & Technical"
    },
    {
      "num": "13",
      "trigger": "Can I change my code / different discount code",
      "tag": "onboarding - code change",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "Yes, subject to availability. Ask for preferred code + SS account email. Warn: old code stops tracking immediately — update all links first.",
      "approachBullets": [
        "Yes — they can change their code (subject to availability)",
        "Ask for: preferred new code + SS account email",
        "Warn: old code stops tracking the moment it changes",
        "Tell them to update bio links, posts, and saved content BEFORE the switch"
      ],
      "macroSheet": "MACROS — Onboarding"
    },
    {
      "num": "14",
      "trigger": "I was recruited by IM8 / you reached out",
      "tag": "seeding - recruited affiliates promise",
      "track": "recruited affiliates",
      "escalate": "No",
      "seeding": "YES — ship immediately",
      "approach": "Honour without conditions. Send gifting form: https://forms.gle/3TKTCjTg8e3bb7ScA. No verification needed.",
      "approachBullets": [
        "Honour the promise without conditions — these are recruited affiliates",
        "Send the gifting form: https://forms.gle/3TKTCjTg8e3bb7ScA",
        "No verification needed"
      ],
      "macroSheet": "MACROS — Product & Seeding"
    },
    {
      "num": "15",
      "trigger": "I hit 5 sales / where is my free product / performance reward / monthly supply",
      "tag": "seeding - monthly tier earned",
      "track": "Any",
      "escalate": "FLAG TO MANAGER",
      "seeding": "YES — process reward",
      "approach": "Process TBD — pending confirmation from manager. Do not action independently. If an affiliate asks about their monthly reward, acknowledge and let them know the team will be in touch at month-end.",
      "approachBullets": [
        "Status: process is TBD, pending confirmation from manager",
        "DO NOT action independently",
        "If they ask: acknowledge the milestone, let them know team will be in touch at month-end"
      ],
      "macroSheet": "MACROS — Reward Claims"
    },
    {
      "num": "16",
      "trigger": "I made my first sale / just got my first sale",
      "tag": "rewards - 1st lifetime sale",
      "track": "Any",
      "escalate": "FLAG TO MANAGER",
      "seeding": "YES — ship 7-day supply + Red Cup",
      "approach": "Process TBD — pending confirmation from manager. If an affiliate reports their 1st sale, congratulate them and let them know their reward will be arranged shortly.",
      "approachBullets": [
        "Status: process is TBD, pending confirmation from manager",
        "DO NOT action independently",
        "If they reach out: congratulate them, let them know reward will be arranged shortly"
      ],
      "macroSheet": "MACROS — Reward Claims"
    },
    {
      "num": "17",
      "trigger": "I've made 3 sales total / just hit 3 lifetime sales",
      "tag": "rewards - 3rd lifetime sale",
      "track": "Any",
      "escalate": "FLAG TO MANAGER",
      "seeding": "YES — ship sample packs + frother",
      "approach": "Process TBD — pending confirmation from manager. If an affiliate reports their 3rd sale, congratulate them and let them know their reward will be arranged shortly.",
      "approachBullets": [
        "Status: process is TBD, pending confirmation from manager",
        "DO NOT action independently",
        "If they reach out: congratulate them, let them know reward will be arranged shortly"
      ],
      "macroSheet": "MACROS — Reward Claims"
    },
    {
      "num": "18",
      "trigger": "I've made 10 sales total / just hit 10 lifetime sales",
      "tag": "rewards - 10th lifetime sale",
      "track": "Any",
      "escalate": "FLAG TO MANAGER",
      "seeding": "YES — ship 30-day supply + merch",
      "approach": "Process TBD — pending confirmation from manager. If an affiliate reports their 10th sale, congratulate them and let them know their reward will be arranged shortly.",
      "approachBullets": [
        "Status: process is TBD, pending confirmation from manager",
        "DO NOT action independently",
        "If they reach out: congratulate them, let them know reward will be arranged shortly"
      ],
      "macroSheet": "MACROS — Reward Claims"
    },
    {
      "num": "19",
      "trigger": "Creator Challenge / completed challenge / how do I claim my prize",
      "tag": "rewards - challenge completion",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "Congratulate. 100 pieces of content = $5,000 USD. Claim via vendor form: https://circleglobal.typeform.com/vendors. Finance requires this before payment.",
      "approachBullets": [
        "Congratulate the affiliate",
        "Confirm the prize: 100 pieces of content = $5,000 USD",
        "Send the vendor form: https://circleglobal.typeform.com/vendors",
        "Finance requires the vendor form before payment is processed"
      ],
      "macroSheet": "MACROS — Reward Claims"
    },
    {
      "num": "20.0",
      "trigger": "I had X sales / old reward structure / previous program",
      "tag": "rewards - legacy claim",
      "track": "Any",
      "escalate": "FLAG TO MANAGER before replying",
      "seeding": "Investigate",
      "approach": "Don't commit. Acknowledge the claim. Ask for sales period and affiliate email. Flag to manager before responding.",
      "approachBullets": [
        "Don't commit to anything",
        "Acknowledge the claim respectfully",
        "Ask for: sales period (month/year) + affiliate email",
        "Flag to manager BEFORE sending any response"
      ],
      "macroSheet": "MACROS — Reward Claims"
    },
    {
      "num": "21",
      "trigger": "Paid partnership / paid deal / want to get paid upfront",
      "tag": "partnership - upgrade",
      "track": "Any",
      "escalate": "FLAG TO MANAGER before replying",
      "seeding": "No",
      "approach": "Don't commit. Flag to manager. Reply only confirms form was shared.",
      "approachBullets": [
        "Don't commit to any terms or amounts",
        "Flag to manager",
        "Reply only confirms the form has been shared"
      ],
      "macroSheet": "MACROS — Partnership Upgrades"
    },
    {
      "num": "22",
      "trigger": "Sponsorship / sponsor our event / organisation",
      "tag": "partnership - sponsorship",
      "track": "Any",
      "escalate": "FLAG TO MANAGER before replying",
      "seeding": "No",
      "approach": "Direct to form: https://form.typeform.com/to/iclm3vWt. No terms or budgets discussed. Flag to manager.",
      "approachBullets": [
        "Direct to the partnership form: https://form.typeform.com/to/iclm3vWt",
        "Do NOT discuss terms or budgets",
        "Flag to manager"
      ],
      "macroSheet": "MACROS — Partnership Upgrades"
    },
    {
      "num": "23",
      "trigger": "Retail / wholesale / stock IM8 / resell",
      "tag": "partnership - retail/wholesale",
      "track": "Any",
      "escalate": "FLAG TO MANAGER before replying",
      "seeding": "No",
      "approach": "Direct to form (select Retail/Wholesale): https://form.typeform.com/to/iclm3vWt. No pricing or MOQ discussion. Flag to manager.",
      "approachBullets": [
        "Direct to the partnership form (select Retail/Wholesale): https://form.typeform.com/to/iclm3vWt",
        "Do NOT discuss pricing or MOQ",
        "Flag to manager"
      ],
      "macroSheet": "MACROS — Partnership Upgrades"
    },
    {
      "num": "24",
      "trigger": "Affiliate replies to monthly commission report / invoice authorising payment (e.g. 'please process', 'go ahead', 'approved', 'please make payment', 'inform me when paid')",
      "tag": "payouts - invoice confirmation",
      "track": "Any",
      "escalate": "No",
      "seeding": "No",
      "approach": "NO REPLY REQUIRED — close the ticket. The affiliate is just confirming the monthly commission report we already sent them. Finance handles the actual payment processing; CS doesn't issue payment confirmation. Even if the affiliate says 'please inform me when paid', finance is the right channel — the affiliate sees the payment land in their PayPal/bank, not via a CS email.",
      "approachBullets": [
        "Affiliate is authorising the commission report we already sent — no CS action needed",
        "Close the ticket. No reply required.",
        "Finance handles the actual payment; do not promise a CS confirmation email",
        "If the affiliate disputes the AMOUNT on the invoice, that's a different case — route to manager"
      ],
      "macroSheet": "MACROS — Payouts & Commission"
    }
  ],
  "macros": [
    {
      "category": "Payouts & Commission",
      "items": [
        {
          "trigger": "What is the minimum payout / when will I get paid?",
          "tag": "payouts - threshold",
          "intent": "Payouts & Commission",
          "response": "Hey [Name],\n\nHere's how payouts work at IM8:\n\nWe pay out monthly — at the end of each calendar month, usually within two weeks. There's a 30-day hold on every sale (that's the refund window clearing), and a $100 USD minimum to trigger a payout. Anything under just rolls over — no expiry, no pressure.\n\nSo if you make a sale in January, the hold clears in February, and you'll see the payout in early March.\n\nOne thing to check first: your payout method needs to be set up in your SS dashboard or payments just queue up. You can sort it here: https://affiliates.socialsnowball.io/auth/affiliate/login\n\nLet me know if anything's not adding up.",
          "responseOriginal": "Hi [Name],\n\nHow payouts work:\n\n• Minimum: $100 USD\n• Schedule: Monthly — end of each calendar month, usually within two weeks\n• Commission hold: 30 days from the date of sale for a refund window to clear\n• Method: PayPal or bank transfer via your SS dashboard\n\nTimeline: sale in January → hold clears February → paid early March. You're typically looking at the month after next for any given sale.\n\nPayout method must be set up in your SS dashboard first — payments queue until it's done: https://affiliates.socialsnowball.io/auth/affiliate/login\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Payout basics",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "What happened to my TUNE balance after the switch to Social Snowball?",
          "tag": "payouts - TUNE migration",
          "intent": "Payouts & Commission",
          "response": "Hey [Name],\n\nGood question — here's the rundown:\n\nOn April 14th we migrated from TUNE Pay to Social Snowball. So:\n\n• Anything earned in TUNE is still being paid out per TUNE's schedule — nothing's lost, you'll get those commissions.\n• Sales from April 14th onwards track in Social Snowball only.\n• Your new dashboard: https://affiliates.socialsnowball.io/auth/affiliate/login\n\nIf you haven't set up your payout method in SS yet, go to the Payout Methods tab and add PayPal or bank details — that way you don't end up with payments queued waiting on it.\n\nLet me know if anything looks off.",
          "responseOriginal": "Hi [Name],\n\nOn April 14th we moved from TUNE Pay to Social Snowball.\n\n• Commissions earned in TUNE: Still paid per TUNE's schedule — nothing lost.\n• Sales from April 14th onwards: Social Snowball only.\n• Your dashboard: https://affiliates.socialsnowball.io/auth/affiliate/login\n\nPayout method not set up in SS yet? Do it now — Payout Methods tab, add PayPal or bank details.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_TUNE migration",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "My dashboard shows different numbers on TUNE vs SS",
          "tag": "payouts - discrepancy",
          "intent": "Payouts & Commission",
          "response": "Hey [Name],\n\nTotally normal — these are two separate platforms that don't sync, so you'll see two different snapshots:\n\n• Before April 14th → TUNE\n• From April 14th onwards → Social Snowball\n\nAdd both together for your full picture. If a specific sale still looks off, send me the date and I'll look into it on my end.",
          "responseOriginal": "Hi [Name],\n\nNot linked — that's expected. Two platforms, two windows:\n\n• Before April 14th → TUNE\n• From April 14th → Social Snowball\n\nAdd both together for your full picture. If a specific sale still looks unaccounted for, send me the date and I'll look into it.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_TUNE vs SS mismatch",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "Social Snowball shows 'no payout methods enabled'",
          "tag": "payouts - SS setup error",
          "intent": "Payouts & Commission",
          "response": "Hey [Name],\n\nAlmost certainly the two-step setup — it catches most people:\n\n1. Log in: https://affiliates.socialsnowball.io/auth/affiliate/login → edit your recipient information → save.\n2. Then in the Payout Methods tab → add PayPal or bank account.\n\nBoth need to be done separately, even though it feels like one flow.\n\nStill seeing the error after that? Reply with a screenshot and I'll help you sort it.",
          "responseOriginal": "Hi [Name],\n\nTwo-step setup — this is the most common issue:\n\nStep 1: https://affiliates.socialsnowball.io/auth/affiliate/login → Edit your recipient information → Save.\nStep 2: Payout Methods tab → add PayPal or bank account.\n\nBoth need to be done separately.\n\nStill showing an error after both? Reply with a screenshot and I'll assist you with it.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "Note from Affiliates Team: \nBackend is still pending compliance & setup completion",
          "gorgiasMacro": "IM8: Affiliate_Payout setup error",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "I haven't been paid / payment is late",
          "tag": "payouts - late payment",
          "intent": "Payouts & Commission",
          "response": "Hey [Name],\n\nLet's get this sorted. Three quick things to check:\n\n1. Is your payout method set up? Payments queue until that's done — Payout Methods tab in your dashboard.\n2. Is your balance above $100 USD? Anything under rolls over to next month.\n3. Are the sales within the 30-day hold window? Commissions from the last 30 days aren't payable yet — they're still clearing the refund window.\n\nIf all three check out and you're still not seeing payment, send me your affiliate ID and the amount you're expecting and I'll look into it on my end.",
          "responseOriginal": "Hi [Name],\n\nThree checks:\n\n1. Payout method set up? Payments queue until it's done.\n2. Above $100 USD? Balances under $100 roll over.\n3. Within the 30-day hold? Commissions from the last 30 days aren't payable yet.\n\nAll clear and still no payment? Send me your affiliate ID and expected amount — I'll check on it.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Late payment",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "I made sales but they're not showing / commission dispute",
          "tag": "payouts - missing commission",
          "intent": "Payouts & Commission",
          "response": "Hey [Name],\n\nLet me help you track this down. A few common reasons a sale might not appear:\n\n• Customer didn't use your discount code or referral link at checkout — sales only track when one of those is present\n• Sale is within the 30-day hold window — commissions from the last 30 days aren't payable yet\n• Sales before April 14th live in TUNE, not SS\n\nIf you can send me the order number (if the customer shared it) and an approximate date of the sale, I'll investigate on my end.",
          "responseOriginal": "Hi [Name],\nA few things that can cause sales not to appear:\n• Customer didn't use your discount code or referral link at checkout — sales only track when one of those is present\n• Sale is within the 30-day hold window — commissions from the last 30 days aren't payable yet\n• Sales before April 14th are in TUNE, not SS\n\nTo look into it, I'll need:\n\nThe order number (if the customer shared it)\nApproximate date of the sale\n\nSend those over and I'll investigate.\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Missing commission",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "What currency are payouts processed in?",
          "tag": "payouts - currency",
          "intent": "Payouts & Commission",
          "response": "Hey [Name],\n\nAll payouts process in USD. If your account is in a different currency, your payment provider handles the conversion on their end.\n\nAnything else I can help with?",
          "responseOriginal": "Hi [Name],\n\nAll payouts are in USD. If your account is in a different currency, your payment provider handles the conversion.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Payout currency",
          "warmed": true,
          "inGorgias": false
        }
      ]
    },
    {
      "category": "Product & Seeding",
      "items": [
        {
          "trigger": "I never received products / is this a product or commission program?",
          "tag": "seeding - program clarity",
          "intent": "Product & Seeding",
          "response": "Hey [Name],\n\nTotally fair question — let me clear it up.\n\nThe IM8 Affiliate Program is commission-based, not a gifting program. You earn 10% on every sale made through your code or referral link — free product isn't part of the signup deal.\n\nThat said, the 10% adds up fast — our top affiliates pull in several thousand dollars a month from their link alone.\n\nYour link: im8health.com/discount/[YOUR CODE]\nYour dashboard: https://affiliates.socialsnowball.io/auth/affiliate/login",
          "responseOriginal": "Hi [Name],\n\nThe IM8 Affiliate Program is commission-based — 10% on every sale through your code or referral link. Free product isn't automatic. It's earned.\n\nHere's how the path works:\n\n2. Make your 1st lifetime sale → 7-day supply + Red Signature Cup ships to you\n3. 3rd lifetime sale → 5x sample packs + Silver frother\n4. 10th lifetime sale → 30-day supply + premium merch\n\nPlus monthly performance rewards at 5, 15, and 30 sales/month.\n\nThe 10% commission adds up fast — our top affiliates earn several thousands a month from their link alone.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Not a gifting program",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "Can I get free samples? / I want to try it before I promote it",
          "tag": "seeding - trial request (inbound affiliates)",
          "intent": "Product & Seeding",
          "response": "Hey [Name],\n\nHonestly — wanting to try it first is exactly the right instinct. The most authentic posts come from people who've actually used the product.\n\nHere's how to get you set up:\n\n• Join our Discord: https://discord.com/invite/tpzwzpWbvs — drop a quick intro in the community\n• Join our Strava club: https://strava.app.link/u94yPNhyb2b — log a workout or post in the club\n• Submit your screenshots: https://forms.gle/hfNbyjGx1DWYsmvK6\n\nOnce we verify you're in both, a free 7-day supply + Red Signature Cup is on its way.",
          "responseOriginal": "Hi [Name],\n\nWanting to try it first is exactly the right instinct — that's what creates authentic content.\n\nHere's your path:\n\n- Join the IM8 Discord: https://discord.com/invite/tpzwzpWbvs — drop an intro post in the community\n- Join the IM8 Strava club: https://strava.app.link/u94yPNhyb2b — log a workout or post in the club\n- Submit your screenshots here: https://forms.gle/hfNbyjGx1DWYsmvK6\n\nOnce verified, a free 7-day supply + Red Signature Cup is on its way to you.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Free samples request",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "I was recruited by IM8 / you reached out and promised a free 7-day supply",
          "tag": "seeding - promise",
          "intent": "Product & Seeding",
          "response": "⚠ CHECK im8hub.com BEFORE REPLYING\nSearch by recipient name or email in the Filters bar. Then:\n\n• No record found → use Scenario B (no shipping details on file yet)\n• Status: PENDING → shipment not yet approved, flag to manager\n• Status: PROCESSING, no tracking number → shipment in progress, use Scenario A\n• Status: PROCESSING with tracking number → shipment dispatched, use Scenario A\n\n---\n\nScenario A (shipment in progress or dispatched)\n\nHey [Name],\n\nThanks for following up — I've checked and your shipment is [in progress / on its way / tracking: TRACKING]. You should see it land within [X] business days.\n\nAny issues, just reply here and I'll sort it.\n---\n\nScenario B (no shipping details on file)\n\nHey [Name],\n\nAbsolutely — let's get this sorted for you.\n\nLooks like we don't have your shipping details on file yet. Drop them here and we'll get it moving straight away: https://forms.gle/3TKTCjTg8e3bb7ScA",
          "responseOriginal": "⚠ CHECK im8hub.com BEFORE REPLYING\nSearch by recipient name or email in the Filters bar. Then:\n\nNo record found → use Scenario A (no shipping details on file)\nStatus: PENDING → shipment not yet approved, flag to manager\nStatus: PROCESSING, no tracking number → shipment in progress, not yet dispatched\nStatus: PROCESSING, tracking number visible → shipment dispatched, use Scenario B\n\n----------\n\nScenario A\nHi [Name],\nThanks for following up — I've checked and your shipment is [in progress / on its way / reference: TRACKING]. You should receive it within [X] business days.\nAny issues, reply here and I'll sort it.\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health\n\n----------\n\nScenario B\nHi [Name],\nAbsolutely — let's get this sorted.\nIt looks like we don't have your shipping details on file yet. Drop them here and we'll get it moving straight away: https://forms.gle/3TKTCjTg8e3bb7ScA\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Recruited — send product",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "Do I need to purchase my own product to be an affiliate?",
          "tag": "seeding - purchase required",
          "intent": "Product & Seeding",
          "response": "Hey [Name],\n\nNope — no purchase needed to join or participate. Share your code or link, earn 10% on every sale. That's it.\n\nIf you want to try IM8 first (great instinct — authentic posts hit harder), here's how to earn a free 7-day supply:\n\n• Join the IM8 Discord: https://discord.com/invite/tpzwzpWbvs — drop a quick intro\n• Join the IM8 Strava club: https://strava.app.link/u94yPNhyb2b — log a workout or post in the club\n• Submit your screenshots: https://forms.gle/hfNbyjGx1DWYsmvK6\n\nOnce we verify, a 7-day supply + Red Signature Cup is on its way.",
          "responseOriginal": "Hi [Name],\n\nNo purchase needed to join or participate. Share your code or link, earn 10% on every sale.\n\nIf you want to try IM8 before promoting it, here's how to earn your free supply:\n\nJoin the IM8 Discord: https://discord.com/invite/tpzwzpWbvs — drop an intro post\nJoin the IM8 Strava club: https://strava.app.link/u94yPNhyb2b — log a workout or post in the club\nSubmit your screenshots here: https://forms.gle/hfNbyjGx1DWYsmvK6\n\nOnce verified, a free 7-day supply + Red Signature Cup ships to you.\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Do I buy my own product",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I've hit 5 sales this month — when do I get my free product?",
          "tag": "seeding - monthly tier earned",
          "intent": "Product & Seeding",
          "response": "Hey [Name],\n\nBig congrats — 5 sales in a month is a real milestone. 🎉\n\nYou've earned your free monthly supply of Daily Ultimate Essentials. Our team will be in touch shortly to arrange shipment.",
          "responseOriginal": "Hi [Name],\n\nCongratulations — 5 sales is a real milestone. 🎉\n\nYou've earned your free monthly supply of Daily Ultimate Essentials. Our team will be in touch shortly to arrange shipment.\n\nWhat's next:\n• 15 sales/month → Essentials + Longevity monthly\n• 30 sales/month → Full Beckham Stack quarterly\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_5 sales this month — reward",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I want to try IM8 but I'm not sure which product is right for me",
          "tag": "seeding - product guidance",
          "intent": "Product & Seeding",
          "response": "Hey [Name],\n\nGreat question — quick breakdown to help you pick:\n\n• Daily Ultimate Essentials — the flagship. 90+ nutrients in one daily sachet covering energy, gut health, immunity, and cognition. This is where almost everyone starts.\n• Longevity — pairs with Essentials. Cellular health, NAD+ support, long-term vitality.\n• The Beckham Stack — both products together. The complete system.\n\nI'd suggest starting with Essentials. And if you complete the activation steps (Discord + Strava posts), you'll earn a free 7-day supply to actually try it.\n\nLet me know if you want more detail on any of them.",
          "responseOriginal": "Hi [Name],\n\nQuick breakdown:\n\n• Daily Ultimate Essentials: The flagship. 90+ nutrients in one daily sachet — energy, gut health, immunity, cognition. Where everyone starts.\n• Longevity: Complements Essentials. Cellular health, NAD+ support, long-term vitality.\n• The Beckham Stack: Both products together — the complete system.\n\nStart with Essentials. Complete the activation steps (Discord + Strava posts) to earn your free 7-day supply.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Which product is right for me",
          "warmed": true,
          "inGorgias": false
        }
      ]
    },
    {
      "category": "Activation Reward",
      "items": [
        {
          "trigger": "Affiliate asks how to unlock activation reward / get free product / activation reward",
          "tag": "activation - how to unlock",
          "intent": "Activation Reward",
          "response": "Hey [Name],\n\nHappy to help — here's exactly how to unlock your activation reward (a free 7-day supply + Red Signature Cup):\n\n1. Join the IM8 Ambassador Discord: https://discord.com/invite/tpzwzpWbvs — drop a quick intro in the community\n2. Join the IM8 Strava club: https://strava.app.link/u94yPNhyb2b — log a workout or post in the club\n3. Submit your screenshots: https://forms.gle/hfNbyjGx1DWYsmvK6\n\nOnce we've verified your posts, your reward ships within 72 hours.",
          "responseOriginal": "Hi [Name],\n\nTo unlock your activation reward — a free 7-day supply + Red Signature Cup — here's what you need to do:\n\n1. Join the IM8 Ambassador Discord: https://discord.com/invite/tpzwzpWbvs — post an intro in the community\n2. Join the IM8 Strava club: https://strava.app.link/u94yPNhyb2b — log a workout or post in the club\n3. Submit your screenshots here: https://forms.gle/hfNbyjGx1DWYsmvK6\n\nOnce we've verified your posts, your reward ships within 72 hours.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Activation — how to unlock",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "Affiliate has submitted the activation form — confirmation",
          "tag": "activation - form submitted",
          "intent": "Activation Reward",
          "response": "Hey [Name],\n\nGot your submission, thanks! We'll verify your Discord and Strava posts in the next few days and ship your reward as soon as it's all good.",
          "responseOriginal": "Hi [Name],\n\nGot your submission — we'll verify your Discord and Strava posts shortly and get your reward on the way.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Activation — form received",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "Activation verified — reward shipping",
          "tag": "activation - verified",
          "intent": "Activation Reward",
          "response": "Hey [Name],\n\nYou're all verified — your 7-day supply + Red Signature Cup is on its way.\n\nWhile you wait, your dashboard and content resources are ready when you are:\n\n• SS dashboard: https://affiliates.socialsnowball.io/auth/affiliate/login\n• Ambassador hub: https://im8ambassador.netlify.app/\n\nReach out if there's anything else I can help with.",
          "responseOriginal": "Hi [Name],\n\nAll verified. Your 7-day supply + Red Signature Cup is on its way.\n\nWhile you wait — your dashboard, referral link, and content resources are all here:\n• SS dashboard: https://affiliates.socialsnowball.io/auth/affiliate/login\n• Ambassador hub: https://im8ambassador.netlify.app/\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Activation — verified & shipping",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "Incomplete submission — posts not found / screenshots missing",
          "tag": "activation - incomplete submission",
          "intent": "Activation Reward",
          "response": "Hey [Name],\n\nThanks for submitting — almost there. We weren't able to verify one or both of your posts.\n\nTo complete activation:\n\n• Discord: make sure your intro post is visible in the IM8 Ambassador server\n• Strava: make sure your activity or post is visible in the IM8 Health club\n\nOnce both are live, resubmit here: https://forms.gle/hfNbyjGx1DWYsmvK6\n\nAny issues, just reply here and we'll sort it.",
          "responseOriginal": "Hi [Name],\n\nThanks for submitting — we weren't able to verify one or both of your posts.\n\nTo complete your activation:\n• Discord: make sure your intro post is visible in the IM8 Ambassador server\n• Strava: make sure your activity or post is visible in the IM8 Health club\n\nOnce both are live, resubmit here: https://forms.gle/hfNbyjGx1DWYsmvK6\n\nAny issues, reply here and we'll sort it.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Activation — incomplete submission",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "Affiliate asks what a 'post' counts as for Discord / Strava",
          "tag": "activation - what counts as post",
          "intent": "Activation Reward",
          "response": "Hey [Name],\n\nGood to check before you submit — here's what counts:\n\n• Discord: a brief intro post in the IM8 Ambassador server. Who you are, what you do, why you're here. A sentence or two is plenty.\n• Strava: a workout log or any activity posted in the IM8 Health club.\n\nOnce both are done, submit your screenshots here: https://forms.gle/hfNbyjGx1DWYsmvK6",
          "responseOriginal": "Hi [Name],\n\nHere's what counts:\n\n• Discord: a brief intro post in the IM8 Ambassador server — who you are, what you do, why you're here. A sentence or two is fine.\n• Strava: a workout log or any activity posted in the IM8 Health club.\n\nOnce both are done, submit your screenshots here: https://forms.gle/hfNbyjGx1DWYsmvK6\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Activation — what counts as a post",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "Affiliate hasn't received reward after 72 hours",
          "tag": "activation - reward delayed",
          "intent": "Activation Reward",
          "response": "Hey [Name],\n\nSorry for the wait — let me chase this down for you. Could you confirm:\n\n1. The email you submitted the form with\n2. Roughly when you submitted\n\nI'll look into it and get back to you.",
          "responseOriginal": "Hi [Name],\n\nApologies for the delay — let me check the status of your submission.\n\nCould you confirm:\n1. The email used when you submitted the form\n2. Approximate date of submission\n\nI'll look into it and get back to you.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Activation — delayed (72hr+)",
          "warmed": true,
          "inGorgias": false
        }
      ]
    },
    {
      "category": "Platform & Technical",
      "items": [
        {
          "trigger": "Are we not using TUNE anymore? Why did we switch?",
          "tag": "technical - TUNE migration",
          "intent": "Platform & Technical",
          "response": "Hey [Name],\n\nGood question. On April 14th we migrated from TUNE Pay to Social Snowball. Here's how it shakes out:\n\n• New sales: Track via your discount code or referral link (im8health.com/discount/[YOUR CODE])\n• Old TUNE links: No longer active for new tracking, but TUNE balance is still being paid per TUNE's schedule — nothing's lost.\n• Your dashboard: https://affiliates.socialsnowball.io/auth/affiliate/login\n\nLet me know if anything looks off.",
          "responseOriginal": "Hi [Name],\n\nOn April 14th we moved from TUNE Pay to Social Snowball.\n\n• New sales: Tracked via your discount code or referral link (im8health.com/discount/[CODE])\n• Old TUNE links: No longer active for new tracking — TUNE balance still paid per TUNE's schedule\n• Your dashboard: https://affiliates.socialsnowball.io/auth/affiliate/login\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Why we switched from TUNE",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "My old TUNE / go2cloud link is broken",
          "tag": "technical - broken TUNE link",
          "intent": "Platform & Technical",
          "response": "Hey [Name],\n\nYeah, old TUNE links (go2cloud.org) aren't active anymore. Your new referral link is:\n\nim8health.com/discount/[YOUR CODE]\n\nWorth swapping it into any bio links, story highlights, or saved posts when you get a moment so you're not losing potential sales.\n\nLet me know if you need anything else.",
          "responseOriginal": "Hi [Name],\n\nOld TUNE links (go2cloud.org) are no longer active. Your new referral link: im8health.com/discount/[YOUR CODE]\n\nUpdate any old links in your bio, stories, or saved posts.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Old TUNE link broken",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "TUNE shows a sale but SS doesn't",
          "tag": "technical - platform discrepancy",
          "intent": "Platform & Technical",
          "response": "Hey [Name],\n\nTotally normal — they're different platforms with different windows:\n\n• Before April 14th → TUNE\n• From April 14th onwards → Social Snowball\n\nAdd both together for the full picture. If you've got a specific post-April-14th sale that's missing, send me the date and I'll look into it.",
          "responseOriginal": "Hi [Name],\n\nNot linked — different platforms, different windows.\n\n• Before April 14th → TUNE\n• From April 14th → Social Snowball\n\nAdd both for your full picture. Specific post-April 14th sale missing? Send me the date.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_TUNE has a sale but SS doesn't",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "Where is my referral link / discount code?",
          "tag": "technical - find link/code",
          "intent": "Platform & Technical",
          "response": "Hey [Name],\n\nEasy fix — here's where they live:\n\n1. Log in: https://affiliates.socialsnowball.io/auth/affiliate/login\n2. On the home screen, you'll see your referral link: im8health.com/discount/[YOUR CODE]\n3. Right below it: your discount code, [YOUR CODE]\n\nEither one will track a sale back to you — use whichever fits the platform you're posting on.",
          "responseOriginal": "Hi [Name],\n\n1. Log in at https://affiliates.socialsnowball.io/auth/affiliate/login\n2. Referral link on the home screen: im8health.com/discount/[YOUR CODE]\n3. Discount code displayed directly below\n\nEither the link or the code tracks a sale to your account.\n\nCan't log in? Send me your signup email.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Where is my link or code",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "I can't log into Social Snowball / forgot password",
          "tag": "technical - SS login",
          "intent": "Platform & Technical",
          "response": "Hey [Name],\n\nLet's get you back in. Here's the quick reset:\n\n1. Go to https://affiliates.socialsnowball.io/auth/affiliate/login\n2. Pop in the email you signed up with\n3. Hit Forgot Password — the reset link comes through within a few minutes\n4. Check your spam folder if it doesn't land in the inbox\n\nStill locked out after that? Send me your signup email and I'll look up your account on my end.",
          "responseOriginal": "Hi [Name],\n\n1. Go to https://affiliates.socialsnowball.io/auth/affiliate/login\n2. Enter your signup email\n3. Click Forgot Password — reset link within a few minutes\n4. Check spam if it doesn't land\n\nStill locked out? Send me your signup email.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Can't log in",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "My SS dashboard isn't showing my recent sales",
          "tag": "technical - missing SS sales",
          "intent": "Platform & Technical",
          "response": "Hey [Name],\n\nLet me help track this down. Three things worth checking:\n\n1. Recent sale? There's up to a 24-hour processing delay before it shows in your dashboard.\n2. Before April 14th? Those sales live in your TUNE dashboard (we migrated to Social Snowball on that date).\n3. Did the customer actually use your code or link at checkout? That's the only way the sale tracks back to you.\n\nIf all three check out and the sales still aren't showing, send over the order numbers and I'll trace them on my end.",
          "responseOriginal": "Hi [Name],\n\nThree things to check:\n\n1. Recent sale? Up to 24-hour processing delay.\n2. Before April 14th? Those are in your TUNE dashboard.\n3. Did the customer use your code or referral link? Sales only track when one of those is present at checkout.\n\nAll clear and still missing? Send me the order numbers.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Sales not showing",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "Can I change my discount code?",
          "tag": "onboarding - code change",
          "intent": "Onboarding",
          "response": "Hey [Name],\n\nYes — you can update your code directly in your SS dashboard. Log in here: https://affiliates.socialsnowball.io/auth/affiliate/login, go to your profile settings, and update it there. (Subject to availability of the new code.)\n\nOne thing to do FIRST: update any bio links, posts, or saved content before you switch — your old code stops tracking the moment it's changed.\n\nReply here if you hit any issues.",
          "responseOriginal": "Hi [Name],\n\nYou can update your code directly in your SS dashboard. Log in at https://affiliates.socialsnowball.io/auth/affiliate/login, go to your profile settings, and update it there. New code is subject to availability.\n\nOne thing to do first: update any bio links, posts, or saved content before switching — your old code stops tracking the moment it's changed.\n\nAny issues, reply here and we'll sort it.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Change my discount code",
          "warmed": true,
          "inGorgias": false
        }
      ]
    },
    {
      "category": "Onboarding",
      "items": [
        {
          "trigger": "I just signed up / how do I get started / what do I do first?",
          "tag": "onboarding - getting started",
          "intent": "Onboarding",
          "response": "Hey [Name],\n\nWelcome to the IM8 affiliate fam — really glad to have you on board. Here's everything you need to get rolling:\n\n1. Your dashboard is your home base: https://affiliates.socialsnowball.io/auth/affiliate/login — your referral link and discount code are right on the home screen.\n2. Your referral link: im8health.com/discount/[YOUR CODE]\n3. Your discount code: [YOUR CODE] — your audience types this at checkout for 10% off.\n4. Want to try IM8 first? Smart move — authentic posts hit harder. Join our Discord (https://discord.com/invite/tpzwzpWbvs) and Strava club (https://strava.app.link/u94yPNhyb2b), drop an intro in both, and we'll send you a 7-day supply + Red Signature Cup so you can experience it yourself.\n5. Content resources: angles, hooks, AI prompts, the whole creator playbook — https://im8ambassador.netlify.app/\n6. Creator Challenge: 100 pieces of content = $5,000 USD. Sign up if you're feeling bold: https://im8creatorportal.vercel.app/\n\nHonestly, the fastest path to your first commission is one real post with your code. Authenticity converts way better than production value every time.\n\nAnything I can help with — just hit reply.",
          "responseOriginal": "Hi [Name], welcome — good to have you.\n\nHere's how to get moving:\n\n1. Dashboard: https://affiliates.socialsnowball.io/auth/affiliate/login — your referral link and discount code are on the home screen.\n2. Your referral link: im8health.com/discount/[YOUR CODE]\n3. Your discount code: [YOUR CODE] — audience uses this at checkout for 10% off.\n4. Unlock your activation reward: Join Discord (https://discord.com/invite/tpzwzpWbvs) + Strava (https://strava.app.link/u94yPNhyb2b) — this is  for trying IM8 yourself. [Verification flow TBD]\n5. Resources: https://im8ambassador.netlify.app/ — content angles, hooks, AI prompts, full playbook.\n6. Creator Challenge: 100 pieces of content = $5,000. Sign up: https://im8creatorportal.vercel.app/\n\nYour reward path as you grow:\n→ 3rd lifetime sale: 5x sample packs + Silver frother\n→ 10th lifetime sale: 30-day supply + premium merch\n\nFastest path to your first commission: one honest post with your code. Authenticity converts better than production value.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Just signed up — what now",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "How does the affiliate program work?",
          "tag": "onboarding - program overview",
          "intent": "Onboarding",
          "response": "Hey [Name],\n\nGreat question. Here's the quick version:\n\nYou earn 10% on every sale made through your code or referral link. That's the deal.\n\n• Your link: im8health.com/discount/[YOUR CODE]\n• Your dashboard (where you track everything): https://affiliates.socialsnowball.io/auth/affiliate/login\n• Payouts: Monthly via PayPal or bank transfer (set this up in your dashboard), $100 USD minimum, with a 30-day hold from each sale to clear the refund window.\n\nSo a sale in January clears in February and pays out in early March.\n\nAnd if you want some firepower for your content: https://im8ambassador.netlify.app/ has angles, hooks, and a full playbook.\n\nAnything else you'd like to look into?",
          "responseOriginal": "Hi [Name],\n\nHow it works:\n\n• Commission: 10% on every sale through your code or referral link\n• Your link: im8health.com/discount/[YOUR CODE]\n• Payouts: Monthly, $100 USD minimum, PayPal or bank via SS\n\nReward path:\n• 1st lifetime sale → 7-day supply + Red Cup\n• 3rd lifetime sale → sample packs + Silver frother\n• 10th lifetime sale → 30-day supply + merch\n• 5 sales/month → free monthly Essentials\n• 15 sales/month → Essentials + Longevity\n• 30 sales/month → Full Beckham Stack quarterly\n\nDashboard: https://affiliates.socialsnowball.io/auth/affiliate/login\nResources: https://im8ambassador.netlify.app/\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_How does the program work",
          "warmed": true,
          "inGorgias": true
        },
        {
          "trigger": "I signed up but haven't received a welcome email / can't find my link",
          "tag": "onboarding - missing welcome",
          "intent": "Onboarding",
          "response": "Hey [Name],\n\nEasy fix — first try your spam folder, the welcome email lands there more often than we'd like.\n\nIf it's not there, you can set your password directly here using your signup email: https://affiliates.socialsnowball.io/auth/affiliate/signup\n\nStill locked out? Send me the email you signed up with and I'll look up your account.",
          "responseOriginal": "Hi [Name],\n\nFirst — check your spam folder.\n\nNot there? Set your password directly into https://affiliates.socialsnowball.io/auth/affiliate/signup using your signup email. \n\nCan't log in? Send me your signup email.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_No welcome email",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "What content should I post / how do I promote IM8?",
          "tag": "onboarding - content guidance",
          "intent": "Onboarding",
          "response": "Hey [Name],\n\nAuthenticity converts way better than production value — consistently. Audiences feel the difference.\n\nA few angles that work for IM8:\n\n1. 90-in-1 simplification — the pill pile vs one sachet. This is the top performer for us.\n2. 30-day timeline — document what actually changed. Day 1 vs Day 30, with honest before/after.\n3. Skeptic-to-believer — lead with your doubt, end with results. Authentic and shareable.\n4. David Beckham angle — strong with sport, lifestyle, and longevity audiences.\n\nThe full 100-piece playbook with hooks, AI prompts, and angles is here: https://im8ambassador.netlify.app/\n\nPick what feels true for you. Authentic always wins.",
          "responseOriginal": "Hi [Name],\n\nAuthenticity converts better than production value — consistently.\n\nAngles that work:\n1. 90-in-1 simplification — the pill pile vs one sachet. IM8's top performer.\n2. 30-day timeline — document what actually changed. Day 1 vs Day 30.\n3. Skeptic-to-believer — lead with your doubt, end with results.\n4. David Beckham angle — strong with sport, lifestyle, and longevity audiences.\n\nFull 100-piece playbook, hooks, and AI prompts: https://im8ambassador.netlify.app/\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_What content should I post",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "Do I need to disclose that I'm an affiliate when I post?",
          "tag": "onboarding - FTC disclosure",
          "intent": "Onboarding",
          "response": "Hey [Name],\n\nYes — FTC and ASA require it whenever you post content where you could earn commission. So any time you share your code or link.\n\n#ad, #advertisement, #affiliate, or a clear verbal mention all work. Just needs to be visible BEFORE your audience engages with the promotion (so not buried in tags at the bottom of a caption).\n\nTransparent creators actually convert better, by the way. Audiences who trust you buy more.",
          "responseOriginal": "Hi [Name],\n\nYes — required by FTC and ASA guidelines whenever you post content where you could earn a commission.\n\n#ad, #advertisement, #affiliate, or a verbal mention works. Just needs to be visible before the audience engages with the promotion.\n\nTransparent creators convert better. Audiences who trust you buy more.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_FTC disclosure",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "Why is the refer-a-friend program 15% / 15%? How is it different from the affiliate program?",
          "tag": "onboarding - program comparison",
          "intent": "Onboarding",
          "response": "Hey [Name],\n\nGreat question — they're two separate programs built for different purposes.\n\nRefer-a-Friend is for IM8 customers who love the product and want to share with people they know personally. When someone uses your referral, they get 15% off — and you get 15% back as a discount on your next purchase. It's a thank-you for sharing within your circle.\n\nThe Affiliate Program is a performance-based earning structure. You earn 10% commission in cash on every sale made through your code or referral link — paid out monthly to PayPal or bank.\n\nThe big difference: refer-a-friend rewards in store credit. Affiliate pays in cash.\n\nIf you're creating content and actively promoting IM8 to an audience, the affiliate program is the one built for you.",
          "responseOriginal": "Hi [Name],\nGreat question — they're two separate programs designed for different purposes.\n\nThe Refer-a-Friend program is for IM8 customers who love the product and want to share it with people they know personally. When someone uses your referral, they get 15% off their order — and you receive 15% back as a discount on your next purchase. It's a thank-you for spreading the word within your circle.\n\nThe Affiliate Program is a performance-based earning structure. You earn 10% commission in cash on every sale made through your discount code or referral link — paid out monthly to your PayPal or bank account.\n\nThe key difference: refer-a-friend rewards you in store credit/discount. The affiliate program pays you in cash.\n\nIf you're actively creating content and promoting IM8 to an audience, the affiliate program is the one built for you.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Affiliate vs refer-a-friend",
          "warmed": true,
          "inGorgias": false
        }
      ]
    },
    {
      "category": "Partnership Upgrades",
      "items": [
        {
          "trigger": "Can we do a paid partnership?",
          "tag": "partnership - upgrade request",
          "intent": "Partnership Upgrades",
          "response": "Hey [Name],\n\nWe work with select creators on paid collaborations — could you share a few things so we can take a proper look?\n\n• How you typically work with brands\n• What you have in mind for IM8 specifically + what success looks like for you\n• Your rate card (so we understand how you structure partnerships)\n• A media kit or platform breakdown if you've got one — reach, audience, channels\n\nOnce I've got that, I'll loop in the right people on our side and we can take it from there.",
          "responseOriginal": "Hi [Name],\n\nWe work with select creators on paid collaborations. \n\nI'd love to understand how you work with brands and what a partnership could look like. Could you share:\n\n- How you typically operate?\n- Your proposal: what you have in mind for IM8 and what success looks like for you\n- Your rate card: so we understand how you structure partnerships\n- A media kit or platform breakdown if you have one: reach, audience, the channels you work across\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Paid partnership request",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I'm a talent manager — my client wants a paid deal",
          "tag": "partnership - talent management",
          "intent": "Partnership Upgrades",
          "response": "Hey [Name],\n\nThanks for reaching out — we work with select creators on paid collaborations. Could you share:\n\n• How your client typically works with brands\n• What you have in mind for IM8 + what success looks like for the partnership\n• Your rate card (so we understand how you structure things)\n• A media kit or platform breakdown — reach, audience, channels\n\nOnce I've got that, I'll route it internally and come back to you.",
          "responseOriginal": "Hi [Name],\n\nWe work with select creators on paid collaborations. \n\nI'd love to understand how you work with brands and what a partnership could look like. Could you share:\n\n- How you typically operate?\n- Your proposal: what you have in mind for IM8 and what success looks like for you\n- Your rate card: so we understand how you structure partnerships\n- A media kit or platform breakdown if you have one: reach, audience, the channels you work across\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Talent manager inquiry",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I want to stock / resell IM8 — retail or wholesale",
          "tag": "partnership - retail/wholesale",
          "intent": "Partnership Upgrades",
          "response": "Hey [Name],\n\nThanks for thinking of us. Retail and wholesale inquiries go through our partnership form — select Retail / Wholesale when you fill it out:\n\nhttps://form.typeform.com/to/iclm3vWt\n\nOur commercial team will follow up directly from there.",
          "responseOriginal": "Hi [Name],\n\nRetail and wholesale inquiries go through our partnership form — select Retail / Wholesale:\nhttps://form.typeform.com/to/iclm3vWt\n\nOur commercial team will follow up.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Retail or wholesale",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "Sponsorship request",
          "tag": "partnership - sponsorship",
          "intent": "Partnership Upgrades",
          "response": "Hey [Name],\n\nThanks for reaching out. Best way to get your proposal in front of the right people is via our partnerships form:\n\nhttps://form.typeform.com/to/iclm3vWt\n\nWhen you fill it out, include event or org details, audience demographics, and any previous brand partners — that helps us assess fast.",
          "responseOriginal": "Hi [Name],\n\nBest way to get your proposal reviewed:\nhttps://form.typeform.com/to/iclm3vWt\n\nInclude event/org details, audience demographics, and previous brand partners.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Sponsorship request",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I want to upgrade from affiliate to ambassador",
          "tag": "partnership - tier upgrade",
          "intent": "Partnership Upgrades",
          "response": "Hey [Name],\n\nLove that you're thinking about levelling up. Higher tiers get reviewed on sales performance, content quality, and audience reach.\n\nThe best path forward is just to keep doing what works — consistent monthly sales and authentic content. Our team watches affiliates hitting their milestones and that's how upgraded conversations get started.\n\nKeep going.",
          "responseOriginal": "Hi [Name],\n\nUpgraded tiers are reviewed on sales performance, content quality, and audience reach.\n\nConsistent monthly sales and authentic content is what gets you noticed — our team watches affiliates hitting their milestones.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Ambassador upgrade",
          "warmed": true,
          "inGorgias": false
        }
      ]
    },
    {
      "category": "Reward Claims",
      "items": [
        {
          "trigger": "I just made my 1st lifetime sale — what do I get?",
          "tag": "rewards - 1st lifetime sale",
          "intent": "Reward Claims",
          "response": "Hey [Name],\n\nYour first sale. That's the one that matters most — you've proven your audience responds to IM8.\n\nYou've unlocked: a free 7-day supply + Red Signature Cup. Fill in your shipping details here and we'll get it moving:\n\nhttps://forms.gle/3TKTCjTg8e3bb7ScA\n\nKeep going.",
          "responseOriginal": "Hi [Name],\n\nYour first sale. That's the one that matters most — you've proven your audience responds to IM8.\n\nYou've unlocked: a free 7-day supply + Red Signature Cup.\n\nFill in your shipping details here and we'll get it moving: https://forms.gle/3TKTCjTg8e3bb7ScA\n\nWhat's next:\n→ 3rd lifetime sale: 5x sample packs + Silver frother\n→ 10th lifetime sale: 30-day supply + premium merch\n→ 5 sales this month: free monthly Essentials supply\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_1st sale — reward",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I just made my 3rd lifetime sale — what do I get?",
          "tag": "rewards - 3rd lifetime sale",
          "intent": "Reward Claims",
          "response": "Hey [Name],\n\n3 lifetime sales — you're building something real here.\n\nYou've unlocked: 5x sample packs + Silver frother. The sample packs are yours to share with your audience (probably the best way to create your next 5 customers). The frother is yours to keep.\n\nShipping details here: https://forms.gle/3TKTCjTg8e3bb7ScA",
          "responseOriginal": "Hi [Name],\n\n3 lifetime sales. You're building something real here.\n\nYou've unlocked: 5x sample packs + Silver frother.\n\nThe sample packs are yours to give to people in your audience — the best way to create your next 5 customers. The frother is yours to keep.\n\nShipping details here: https://forms.gle/3TKTCjTg8e3bb7ScA\n\nNext unlock: 10th lifetime sale → 30-day supply + premium merch.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_3rd sale — reward",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I just made my 10th lifetime sale — what do I get?",
          "tag": "rewards - 10th lifetime sale",
          "intent": "Reward Claims",
          "response": "Hey [Name],\n\n10 lifetime sales — that's a real achievement. You've generated meaningful revenue for the brand and made it look easy.\n\nYou've unlocked: 30-day supply + premium merch [item TBD]. Shipping details here:\n\nhttps://forms.gle/3TKTCjTg8e3bb7ScA\n\nAt this level you're on our radar for higher-tier conversations. Keep doing what you're doing.",
          "responseOriginal": "Hi [Name],\n\n10 lifetime sales. That's a real achievement — and you've generated serious revenue for the brand.\n\nYou've unlocked: 30-day supply + premium merch [item TBD].\n\nShipping details here: https://forms.gle/3TKTCjTg8e3bb7ScA\n\nAt this level you're on our radar for higher-tier conversations. Keep going.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_10th sale — reward",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I hit my monthly sales milestone — how do the product rewards work?",
          "tag": "rewards - monthly tier mechanics",
          "intent": "Reward Claims",
          "response": "Hey [Name],\n\nHere's how the monthly performance rewards work:\n\n• 5 sales/month → Free monthly Daily Ultimate Essentials (your flavour choice)\n• 15 sales/month → Essentials + Longevity monthly\n• 30 sales/month → Full Beckham Stack quarterly (3-month supply, 4 deliveries per year)\n\nSubmit your shipping and flavour preference here: https://forms.gle/3TKTCjTg8e3bb7ScA\n\nOne thing worth knowing: if you miss a month, the reward just pauses — it doesn't cancel. Hit the threshold again and it reactivates straight away.",
          "responseOriginal": "Hi [Name],\n\nMonthly reward tiers:\n\n• 5 sales/month: Free monthly Daily Ultimate Essentials (flavour choice)\n• 15 sales/month: Essentials + Longevity monthly\n• 30 sales/month: Full Beckham Stack quarterly (3-month supply, 4 deliveries/year)\n\nSubmit shipping and flavour details here: https://forms.gle/3TKTCjTg8e3bb7ScA\n\nGrace period: miss a month, your reward pauses — not cancels. Reactivates when you hit the threshold again.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Monthly tier — how it works",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I completed the Creator Challenge — how do I claim my $5,000?",
          "tag": "rewards - creator challenge",
          "intent": "Reward Claims",
          "response": "Hey [Name],\n\nBig congratulations — 100 pieces of content is no small thing. 🎉\n\nTo receive your $5,000 USD prize, complete the vendor registration form (finance requires this before payment is processed):\n\nhttps://circleglobal.typeform.com/vendors\n\nPayments process within [X] business days once the form is in.\n\nProud of you.",
          "responseOriginal": "Hi [Name],\n\nCongratulations — 100 pieces of content is no small thing. 🎉\n\nTo receive your $5,000 prize, complete the vendor registration form — finance requires this before payment is processed:\nhttps://circleglobal.typeform.com/vendors\n\nPayments processed within [X] business days once submitted.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Creator Challenge prize",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I had X sales under the old program — legacy reward claim",
          "tag": "rewards - legacy claim",
          "intent": "Reward Claims",
          "response": "Hey [Name],\n\nThanks for flagging — we honour every reward earned.\n\nTo verify your claim, could you share:\n\n1. The time period the sales were made (month and year)\n2. The email address on your affiliate account\n\nOnce I've got that, I'll cross-check against our records and get back to you.\n\nAppreciate your patience.",
          "responseOriginal": "Hi [Name],\n\nWe honour every reward earned.\n\nTo verify your claim:\n1. Time period the sales were made (month and year)\n2. Email address on your affiliate account\n\nI'll confirm against our records and get back to you. Appreciate your patience.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Legacy reward claim",
          "warmed": true,
          "inGorgias": false
        },
        {
          "trigger": "I qualified for a reward but haven't received it",
          "tag": "rewards - late reward",
          "intent": "Reward Claims",
          "response": "Hey [Name],\n\nLet me chase this down. Could you share:\n\n1. Which milestone or tier, and which month\n2. Whether you've submitted the reward form: https://forms.gle/3TKTCjTg8e3bb7ScA\n3. The email on your affiliate account\n\nI'll check the status and follow up.",
          "responseOriginal": "Hi [Name],\n\nLet's look into this. Could you share:\n\n1. Which milestone or tier and which month\n2. Whether you've submitted the reward form: https://forms.gle/3TKTCjTg8e3bb7ScA\n3. Email on your affiliate account\n\nI'll check the status and follow up.\n\nWith Health,\n[Your name]\nThe Affiliates Team @ IM8 Health",
          "note": "",
          "gorgiasMacro": "IM8: Affiliate_Reward missing",
          "warmed": true,
          "inGorgias": false
        }
      ]
    }
  ],
  "links": [
    {
      "heading": "Links",
      "items": [
        {
          "title": "Title",
          "url": "Link",
          "purpose": "What it's for"
        }
      ]
    },
    {
      "heading": "INTERNAL — CS USE ONLY, DO NOT SHARE WITH AFFILIATES",
      "items": [
        {
          "title": "SS Admin Login",
          "url": "https://admin.socialsnowball.io/auth/login",
          "purpose": "Backend system of Social Snowball. Sign in via Shopify (uses the IM8 store login). Request access via Jira if you can't get in."
        },
        {
          "title": "IM8 Shopify Admin",
          "url": "https://im8store.myshopify.com",
          "purpose": "The Shopify admin used to authenticate into SS Admin. Same Shopify staff credentials."
        },
        {
          "title": "Internal Gifting Hub",
          "url": "https://im8hub.com/",
          "purpose": "Internal hub for managing gifting campaigns."
        }
      ]
    },
    {
      "heading": "AFFILIATE PROGRAMME",
      "items": [
        {
          "title": "SS Signup — New Affiliates",
          "url": "https://im8health.socialsnowball.io/signup/bcdd67d9-5310-490b-8b05-e13e273af2e5",
          "purpose": "Send to anyone who wants to join. This is the entry point."
        },
        {
          "title": "SS Login — Set Password",
          "url": "https://affiliates.socialsnowball.io/auth/affiliate/signup",
          "purpose": "Where affiliates, after signing up, set their password to log into their account"
        },
        {
          "title": "SS Login — Affiliate Dashboard",
          "url": "https://affiliates.socialsnowball.io/auth/affiliate/login",
          "purpose": "Where affiliates access their link, code, sales, and payout setup. Send when they can't find their link or code."
        },
        {
          "title": "Ambassador Programme Landing Page",
          "url": "https://im8health.com/pages/im8-ambassador-program",
          "purpose": "Public-facing programme page. Good for context when onboarding new affiliates."
        },
        {
          "title": "Ambassador Hub",
          "url": "https://im8ambassador.netlify.app/",
          "purpose": "Creator resource centre: content angles, hooks, AI prompts, brand assets, quick-start checklist, 100-piece playbook. Always point affiliates here for content guidance."
        },
        {
          "title": "Creator Challenge Portal",
          "url": "https://im8creatorportal.vercel.app/",
          "purpose": "Sign-up portal for the Creator Challenge: 100 pieces of content = $5,000 USD. Open to all affiliates, ongoing."
        },
        {
          "title": "Support — Email & Discord",
          "url": "Discord (discord.com/invite/tpzwzpWbvs) #general-questions — direct affiliates here first for quick questions, community support, and general program queries. Fastest response.\n\nEmail (affiliates@im8health.com) — for formal inquiries, account issues, reward claims, and anything that needs a paper trail.",
          "purpose": "Direct affiliate support. Use for escalations or when pointing an affiliate to support outside email triage."
        }
      ]
    },
    {
      "heading": "ACTIVATION — DISCORD + STRAVA",
      "items": [
        {
          "title": "Discord — Ambassador Community",
          "url": "https://discord.com/invite/tpzwzpWbvs",
          "purpose": "Required for activation reward unlock. Also: weekly briefs, early campaign access, peer community. Always send to new affiliates and any inbound affiliate asking about free product."
        },
        {
          "title": "Strava — IM8 Ambassador Club",
          "url": "https://strava.app.link/u94yPNhyb2b",
          "purpose": "Required for activation reward unlock alongside Discord. Good touchpoint for fitness/wellness creators. Send alongside Discord link."
        }
      ]
    },
    {
      "heading": "GIFTING & REWARDS",
      "items": [
        {
          "title": "Activation Reward Form",
          "url": "https://forms.gle/hfNbyjGx1DWYsmvK6",
          "purpose": "Send to ALL inbound affiliates claiming the activation reward (Discord + Strava + post in both). This is the NEW form — not the general gifting form. Submitting this form triggers the 72-hour verification check before the 7-day supply + Red Cup ships."
        },
        {
          "title": "Gifting Form — 30-Pack Variety Starter Kit",
          "url": "https://forms.gle/2MygqRp8VxWJtcSt5",
          "purpose": "For 30-pack gifting. Use when the brief calls for the variety starter kit specifically."
        },
        {
          "title": "Vendor Registration Form",
          "url": "https://circleglobal.typeform.com/vendors",
          "purpose": "Required by finance before any cash prize is paid out. Send to affiliates claiming Creator Challenge prize or any cash reward. Must be completed before payment is processed."
        }
      ]
    },
    {
      "heading": "CONTENT & BRAND ASSETS",
      "items": []
    },
    {
      "heading": "Ambassador Playbook (PDF)",
      "items": [
        {
          "title": "Brand Asset Drive",
          "url": "https://drive.google.com/drive/folders/1Z8-qtFWtwIH8JWGOFtL5Qh5tQOjfJbFy",
          "purpose": "Official logos, product imagery, colour codes, usage guidelines."
        },
        {
          "title": "Social Assets Drive",
          "url": "https://drive.google.com/drive/folders/1gyRvu4B05oVfGsKuCOpYzY1Vfxjy2ie4",
          "purpose": "Ready-to-use graphics sized for Instagram, TikTok, and Stories."
        },
        {
          "title": "Product Photography Library",
          "url": "https://drive.google.com/drive/folders/1qnrZ5HxjdAQWF_nDGRnInRKKqzYuwzH6",
          "purpose": "High-res product shots of DUE, DUL, and the Beckham Stack."
        },
        {
          "title": "Captions & Hooks Doc",
          "url": "https://docs.google.com/document/d/16UYMmD9OZwJQO77N2YqzEADJEpLXXepA/edit",
          "purpose": "Plug-and-play captions for all 7 content angles."
        },
        {
          "title": "Creator Video Library",
          "url": "https://drive.google.com/drive/folders/1JfVOIg830RB_thwkaGIiQ64QNIuOBYbm",
          "purpose": "Product videos, B-roll, and brand content affiliates can use in their own edits."
        },
        {
          "title": "IM8 Insight Portal",
          "url": "https://insight.im8.digital/reports/top50?account=IM8-USD&sort=avg_hook_rate&days=30",
          "purpose": "Live top 50 creator rankings by hook rate, engagement, and sales. \nOpen to share to all. \n\nLogin: \nUsername: im8ugc\nPW: im8ugc"
        },
        {
          "title": "IM8 Website",
          "url": "https://im8health.com",
          "purpose": "Main storefront. Direct affiliates here for purchases, especially inbound affiliates using the activation reward."
        }
      ]
    }
  ]
};
