// Demo seed rows for every log type.
//
// All fictional LUMÉ demo content. Shapes match exactly what each log
// form POSTs (and what Records / Reports read) — no legacy field names.
// Dates are relative (see lib/demo-dates.js) with the same distribution
// per log type: 2 today · 3 within 1–3 days · 4 within 4–7 days ·
// remainder 8–30 days. Every "last 7 days" view therefore always shows
// at least 3 records, on any date, forever.
//
// Values that back a select (category, cancellationType, scope, theme,
// severity, resolution, status, complaintMethod) store the form's option
// value; the UI always renders them through their label maps. Reason
// arrays (reasonMains / reasonSubs) store display labels directly.

import { hoursAgo, daysAgo, dateDaysAgo, warehouseFromCountry } from "./demo-dates.js";

const wh = warehouseFromCountry;

// ─── Order Issues ────────────────────────────────────────────────────────────
export function issuesSeed() {
  return [
    { id: "demo-iss-001", createdAt: hoursAgo(0, 25), orderId: "#LME-10482", ticketId: "4821", customerName: "Chloe Fitzpatrick", customerEmail: "chloe.fitzpatrick@example.com", country: "AU", warehouse: wh("AU"), category: "broken-pump", severity: "normal", description: "Smooth Serum arrived with the pump mechanism snapped off at the neck. Photo provided — pump head detached in the box.", resolution: "replacement", resolutionNotes: "Replacement dispatched same day. No return required.", itemsAffected: ["Smooth Serum x1"], agent: "demo" },
    { id: "demo-iss-002", createdAt: hoursAgo(4, 10), orderId: "#LME-10479", ticketId: "4816", customerName: "James Okafor", customerEmail: "james.okafor@example.com", country: "US", warehouse: wh("US"), category: "wrong-item", severity: "normal", description: "Customer ordered Repair Serum, received Glow Serum. Confirmed from photo of the box label.", resolution: "replacement", resolutionNotes: "Correct Repair Serum sent. Customer keeping the Glow Serum as a gift.", itemsAffected: ["Repair Serum x1"], agent: "demo" },
    { id: "demo-iss-003", createdAt: daysAgo(1, 16, 45), orderId: "#LME-10461", ticketId: "4802", customerName: "Sophie Brennan", customerEmail: "sophie.brennan@example.com", country: "GB", warehouse: wh("GB"), category: "wrong-item", severity: "normal", description: "Hair Edit box contained Smooth + Scalp Serums. Customer's hair profile shows Repair + Glow. Fulfilment mismatch.", resolution: "replacement", resolutionNotes: "Correct serums sent. Ops flagged to check this month's batch for further mismatches.", itemsAffected: ["Repair Serum x1", "Glow Serum x1"], agent: "demo" },
    { id: "demo-iss-004", createdAt: daysAgo(2, 11, 20), orderId: "#LME-10447", ticketId: "4788", customerName: "Marcus Webb", customerEmail: "marcus.webb@example.com", country: "AU", warehouse: wh("AU"), category: "leaked-bottle", severity: "high", description: "Scalp Serum bottle leaked inside the sealed shipping box. Approximately 30% of product lost. Photos provided.", resolution: "refund", resolutionNotes: "Full refund processed due to extent of damage. Customer offered 20% off next order.", itemsAffected: ["Scalp Serum x1"], agent: "demo" },
    { id: "demo-iss-005", createdAt: daysAgo(3, 14, 5), orderId: "#LME-10433", ticketId: "4771", customerName: "Priya Nair", customerEmail: "priya.nair@example.com", country: "AU", warehouse: wh("AU"), category: "crushed-packaging", severity: "normal", description: "Outer box arrived crushed — product intact but presentation damaged. Customer was gifting it.", resolution: "replacement", resolutionNotes: "Replacement sent in gift-ready packaging with a handwritten note.", itemsAffected: ["Smooth Serum x1", "Glow Serum x1"], agent: "demo" },
    { id: "demo-iss-006", createdAt: daysAgo(4, 9, 30), orderId: "#LME-10421", ticketId: "4763", customerName: "Georgia Whitfield", customerEmail: "georgia.whitfield@example.com", country: "AU", warehouse: wh("AU"), category: "missing-item", severity: "normal", description: "Hair Edit box arrived with only two of three serums — Glow Serum missing from the insert.", resolution: "replacement", resolutionNotes: "Missing Glow Serum shipped express. Packing line notified.", itemsAffected: ["Glow Serum x1"], agent: "demo" },
    { id: "demo-iss-007", createdAt: daysAgo(5, 15, 15), orderId: "#LME-10412", ticketId: "4747", customerName: "Fatima Al-Hassan", customerEmail: "fatima.alhassan@example.com", country: "US", warehouse: wh("US"), category: "damaged-item", severity: "normal", description: "Repair Serum bottle cracked along the base — product usable but seeping slowly. Photo confirmed.", resolution: "replacement", resolutionNotes: "Replacement dispatched. Customer advised to decant remaining product.", itemsAffected: ["Repair Serum x1"], agent: "demo" },
    { id: "demo-iss-008", createdAt: daysAgo(6, 10, 50), orderId: "#LME-10405", ticketId: "4739", customerName: "Liam O'Brien", customerEmail: "liam.obrien@example.com", country: "GB", warehouse: wh("GB"), category: "leaked-bottle", severity: "normal", description: "Glow Serum lid not fully sealed — light leak contained by the inner wrap. Minimal product loss.", resolution: "gift", resolutionNotes: "Kept as-is at customer's request. Free Glow Serum added to next Hair Edit box.", itemsAffected: ["Glow Serum x1"], agent: "demo" },
    { id: "demo-iss-009", createdAt: daysAgo(7, 13, 25), orderId: "#LME-10398", ticketId: "4726", customerName: "Zoe Andersen", customerEmail: "zoe.andersen@example.com", country: "AU", warehouse: wh("AU"), category: "broken-pump", severity: "low", description: "Smooth Serum pump stiff and misfiring — dispenses on second press only.", resolution: "replacement", resolutionNotes: "Pump-only replacement sent (caps are interchangeable).", itemsAffected: ["Smooth Serum x1"], agent: "demo" },
    { id: "demo-iss-010", createdAt: daysAgo(12, 10, 0), orderId: "#LME-10361", ticketId: "4688", customerName: "Daniel Torres", customerEmail: "daniel.torres@example.com", country: "US", warehouse: wh("US"), category: "wrong-item", severity: "normal", description: "Hair Edit box curated for fine hair but customer profile is coily — wrong pairing shipped after profile update.", resolution: "replacement", resolutionNotes: "Correct pairing sent. Profile-sync issue raised with Ops.", itemsAffected: ["The Hair Edit (Subscription Box) x1"], agent: "demo" },
    { id: "demo-iss-011", createdAt: daysAgo(19, 15, 40), orderId: "#LME-10312", ticketId: "4611", customerName: "Niamh O'Sullivan", customerEmail: "niamh.osullivan@example.com", country: "GB", warehouse: wh("GB"), category: "damaged-item", severity: "high", description: "Scalp Serum bottle shattered in transit — glass through the mailer. Customer unharmed, photos on file.", resolution: "refund", resolutionNotes: "Full refund plus replacement sent with reinforced packaging. Carton spec flagged to Parcelline.", itemsAffected: ["Scalp Serum x1"], agent: "demo" },
    { id: "demo-iss-012", createdAt: daysAgo(26, 11, 10), orderId: "#LME-10255", ticketId: "4530", customerName: "Amelia Cross", customerEmail: "amelia.cross@example.com", country: "AU", warehouse: wh("AU"), category: "tampered-package", severity: "high", description: "Outer seal broken and resealed with clear tape on arrival. Contents complete but customer uncomfortable using them.", resolution: "replacement", resolutionNotes: "Fresh box shipped. Incident logged with Parcelline Sydney for the courier chain.", itemsAffected: ["The Hair Edit (Subscription Box) x1"], agent: "demo" },
  ];
}

// ─── Replacements ────────────────────────────────────────────────────────────
export function replacementsSeed() {
  return [
    { id: "demo-rep-001", createdAt: hoursAgo(0, 35), orderId: "#LME-10485", ticketId: "4825", customerName: "Casey Kim", country: "US", warehouse: wh("US"), reasonMains: ["Damaged Item"], reasonSubs: ["Leaked bottle (in transit)"], itemsAffected: ["Scalp Serum x1"], details: "Scalp Serum leaked through the shipper — around a quarter of the bottle lost. Photo confirmed.", solution: "Replacement dispatched same day.", agent: "demo" },
    { id: "demo-rep-002", createdAt: hoursAgo(5, 30), orderId: "#LME-10483", ticketId: "4823", customerName: "Riley Watson", country: "AU", warehouse: wh("AU"), reasonMains: ["Lost Package"], reasonSubs: ["Confirmed by courier"], itemsAffected: ["Smooth Serum x1"], details: "Courier confirmed the parcel as lost. Customer provided the tracking screenshot.", solution: "Replacement shipped express.", agent: "demo" },
    { id: "demo-rep-003", createdAt: daysAgo(1, 9, 15), orderId: "#LME-10466", ticketId: "4806", customerName: "Drew Patel", country: "GB", warehouse: wh("GB"), reasonMains: ["Missing Item"], reasonSubs: ["Glow Serum"], itemsAffected: ["Glow Serum x1"], details: "Only two of three ordered items arrived. Confirmed from the unboxing video.", solution: "Missing serum shipped.", agent: "demo" },
    { id: "demo-rep-004", createdAt: daysAgo(2, 14, 40), orderId: "#LME-10452", ticketId: "4791", customerName: "Maddison Clarke", country: "AU", warehouse: wh("AU"), reasonMains: ["Wrong Product / Wrong Serums"], reasonSubs: ["Fulfilment error"], itemsAffected: ["Repair Serum x1"], details: "Ordered Repair Serum, received Smooth. Box label matches order, contents don't.", solution: "Correct serum sent. Customer keeping the extra.", agent: "demo" },
    { id: "demo-rep-005", createdAt: daysAgo(3, 11, 0), orderId: "#LME-10441", ticketId: "4779", customerName: "Ethan Rhodes", country: "US", warehouse: wh("US"), reasonMains: ["Damaged Packaging"], reasonSubs: ["Gifting packaging damaged"], itemsAffected: ["The Hair Edit (Subscription Box) x1"], details: "Gift order — outer presentation box crushed in transit. Product fine, presentation ruined.", solution: "Gift-ready replacement sent with a handwritten note.", agent: "demo" },
    { id: "demo-rep-006", createdAt: daysAgo(4, 16, 20), orderId: "#LME-10430", ticketId: "4768", customerName: "Charlotte Ellery", country: "GB", warehouse: wh("GB"), reasonMains: ["Shipment Delay"], reasonSubs: [">2 weeks"], itemsAffected: ["Scalp Serum x1"], details: "No tracking movement for 16 days out of London. Customer needs it before travel.", solution: "Replacement shipped express; original to be returned to sender if it surfaces.", agent: "demo" },
    { id: "demo-rep-007", createdAt: daysAgo(5, 10, 45), orderId: "#LME-10419", ticketId: "4755", customerName: "Harper Quinn", country: "US", warehouse: wh("US"), reasonMains: ["Lost Package"], reasonSubs: ["Misdelivery"], itemsAffected: ["Glow Serum x1", "Smooth Serum x1"], details: "Delivered photo shows a different porch. Courier investigating; customer without product.", solution: "Replacement sent without waiting on the courier claim.", agent: "demo" },
    { id: "demo-rep-008", createdAt: daysAgo(6, 13, 30), orderId: "#LME-10409", ticketId: "4742", customerName: "Jack Halloran", country: "AU", warehouse: wh("AU"), reasonMains: ["Damaged Item"], reasonSubs: ["Cracked bottle"], itemsAffected: ["Repair Serum x1"], details: "Hairline crack at the shoulder of the bottle — slow seep into the box liner.", solution: "Replacement dispatched. Photos added to the Parcelline claim file.", agent: "demo" },
    { id: "demo-rep-009", createdAt: daysAgo(7, 9, 50), orderId: "#LME-10396", ticketId: "4722", customerName: "Freya Dunbar", country: "GB", warehouse: wh("GB"), reasonMains: ["Goodwill / Token of Appreciation"], reasonSubs: ["Apology for poor experience"], itemsAffected: ["Glow Serum x1"], details: "Two delayed boxes in a row for a 14-month subscriber. Goodwill gesture approved by Lead.", solution: "Complimentary Glow Serum added to next renewal.", agent: "demo" },
    { id: "demo-rep-010", createdAt: daysAgo(14, 12, 10), orderId: "#LME-10344", ticketId: "4655", customerName: "Mia Castellanos", country: "US", warehouse: wh("US"), reasonMains: ["Wrong Address"], reasonSubs: ["Customer error"], itemsAffected: ["The Hair Edit (Subscription Box) x1"], details: "Customer moved and forgot to update the subscription address. Box delivered to the old flat.", solution: "Replacement to the new address; address updated on the subscription.", agent: "demo" },
    { id: "demo-rep-011", createdAt: daysAgo(23, 15, 35), orderId: "#LME-10287", ticketId: "4571", customerName: "Oliver Bennett", country: "GB", warehouse: wh("GB"), reasonMains: ["RTS (Return to Sender)"], reasonSubs: ["No reason stated"], itemsAffected: ["Smooth Serum x1"], details: "Parcel bounced back to the London warehouse unopened, no carrier note.", solution: "Re-shipped after confirming the address with the customer.", agent: "demo" },
  ];
}

// ─── Cancellations ───────────────────────────────────────────────────────────
export function cancellationsSeed() {
  return [
    { id: "demo-can-001", createdAt: hoursAgo(1, 5), orderId: "#LME-10486", ticketId: "4827", customerName: "Amelia Cross", customerEmail: "amelia.cross@example.com", country: "AU", cancellationType: "too-expensive", scope: "subscription", notes: "Saved — customer agreed to a 2-month pause instead. Will reactivate in September; loyalty code sent for her return.", agent: "demo" },
    { id: "demo-can-002", createdAt: hoursAgo(3, 45), orderId: "#LME-10481", ticketId: "4819", customerName: "Daniel Torres", customerEmail: "daniel.torres@example.com", country: "US", cancellationType: "wrong-serums", scope: "subscription", notes: "Saved — formula swap. Colour-treated hair but receiving Smooth; profile updated, swapped to Repair + Glow. Very happy.", agent: "demo" },
    { id: "demo-can-003", createdAt: daysAgo(1, 10, 15), orderId: "#LME-10464", ticketId: "4804", customerName: "Niamh O'Sullivan", customerEmail: "niamh.osullivan@example.com", country: "GB", cancellationType: "not-using-fast-enough", scope: "subscription", notes: "Saved — still has 2 bottles from last box. Switched to bi-monthly shipping; happy to continue at reduced frequency.", agent: "demo" },
    { id: "demo-can-004", createdAt: daysAgo(2, 16, 20), orderId: "#LME-10450", ticketId: "4790", customerName: "Ryan Kowalski", customerEmail: "ryan.kowalski@example.com", country: "US", cancellationType: "no-results-seen", scope: "subscription", notes: "Declined save. At 6 weeks with no visible change — was applying to dry hair instead of damp. Explained the routine; customer still cancelled. Refund processed.", agent: "demo" },
    { id: "demo-can-005", createdAt: daysAgo(3, 9, 30), orderId: "#LME-10437", ticketId: "4775", customerName: "Isla Mackenzie", customerEmail: "isla.mackenzie@example.com", country: "AU", cancellationType: "personal-life-change", scope: "subscription", notes: "Declined pause — moving overseas and didn't want to manage it remotely. Cancelled with a warm sendoff.", agent: "demo" },
    { id: "demo-can-006", createdAt: daysAgo(4, 13, 40), orderId: "#LME-10425", ticketId: "4765", customerName: "Ruby Tran", customerEmail: "ruby.tran@example.com", country: "AU", cancellationType: "too-expensive", scope: "subscription", notes: "Saved — moved from monthly to bi-monthly Hair Edit. Kept the subscription at roughly half the monthly spend.", agent: "demo" },
    { id: "demo-can-007", createdAt: daysAgo(5, 11, 25), orderId: "#LME-10415", ticketId: "4751", customerName: "Noah Whitmore", customerEmail: "noah.whitmore@example.com", country: "US", cancellationType: "switching-brand", scope: "subscription", notes: "Declined save. Moving to a salon-prescribed routine. Left on good terms — asked to keep the win-back list option open.", agent: "demo" },
    { id: "demo-can-008", createdAt: daysAgo(6, 15, 10), orderId: "#LME-10402", ticketId: "4735", customerName: "Poppy Ashworth", customerEmail: "poppy.ashworth@example.com", country: "GB", cancellationType: "no-results-seen", scope: "subscription", notes: "Saved — at week 3, expected the 4–6 week curve. Walked through the timeline and routine check; agreed to continue to week 6.", agent: "demo" },
    { id: "demo-can-009", createdAt: daysAgo(7, 10, 55), orderId: "#LME-10393", ticketId: "4719", customerName: "Sophie Brennan", customerEmail: "sophie.brennan@example.com", country: "GB", cancellationType: "wrong-serums", scope: "subscription", notes: "Saved — curation mismatch after a keratin treatment. Swapped the Edit pairing to Smooth + Glow.", agent: "demo" },
    { id: "demo-can-010", createdAt: daysAgo(11, 14, 0), orderId: "#LME-10358", ticketId: "4680", customerName: "Ben Cartwright", customerEmail: "ben.cartwright@example.com", country: "US", cancellationType: "address-change", scope: "order", notes: "Order cancelled before dispatch — customer relocating and re-ordered to the new address the same day.", agent: "demo" },
    { id: "demo-can-011", createdAt: daysAgo(18, 9, 45), orderId: "#LME-10309", ticketId: "4607", customerName: "Harlow James", customerEmail: "harlow.james@example.com", country: "AU", cancellationType: "not-using-fast-enough", scope: "subscription", notes: "Saved — skipped one month. Reminder set to check in before the next renewal.", agent: "demo" },
    { id: "demo-can-012", createdAt: daysAgo(27, 16, 30), orderId: "#LME-10248", ticketId: "4522", customerName: "Finley Carter", customerEmail: "finley.carter@example.com", country: "US", cancellationType: "too-expensive", scope: "both", notes: "Declined save. Budget cut across all subscriptions. Added to the win-back list with a 15% return offer.", agent: "demo" },
  ];
}

// ─── Feedback ────────────────────────────────────────────────────────────────
export function feedbackSeed() {
  return [
    { id: "demo-fb-001", createdAt: hoursAgo(0, 45), orderId: "#LME-10480", ticketId: "4818", customerName: "Georgia Whitfield", customerEmail: "georgia.whitfield@example.com", country: "AU", theme: "product", relatedTeam: "Product", details: "Customer emailed unprompted to say her hair is 'completely transformed' after 6 weeks of Repair Serum. Previously had very damaged bleached hair. Wants to share her experience.", suggestion: "Invite her onto the reviews page — strong before/after story.", agent: "demo" },
    { id: "demo-fb-002", createdAt: hoursAgo(6, 0), orderId: "#LME-10478", ticketId: "4814", customerName: "Liam O'Brien", customerEmail: "liam.obrien@example.com", country: "GB", theme: "marketing", relatedTeam: "Marketing", details: "Customer unhappy that the Scalp Serum tingling was not mentioned prominently on the product page. Felt alarmed the first time it happened. Fine once explained, but wants better upfront communication.", suggestion: "Add a 'what to expect' tingling callout to the Scalp Serum PDP.", agent: "demo" },
    { id: "demo-fb-003", createdAt: daysAgo(1, 14, 50), orderId: "#LME-10462", ticketId: "4803", customerName: "Fatima Al-Hassan", customerEmail: "fatima.alhassan@example.com", country: "US", theme: "product", relatedTeam: "Product", details: "Requesting travel-size versions of Smooth and Glow Serums. Loves the products but can't take full bottles in hand luggage.", suggestion: "Travel minis — repeat request, third this month.", agent: "demo" },
    { id: "demo-fb-004", createdAt: daysAgo(2, 10, 30), orderId: "#LME-10453", ticketId: "4793", customerName: "Zoe Andersen", customerEmail: "zoe.andersen@example.com", country: "AU", theme: "loyalty", relatedTeam: "Marketing", details: "Customer DM'd on Instagram saying she recommended LUMÉ to 4 friends this week after seeing results from Glow Serum. Referral code shared with her.", agent: "demo" },
    { id: "demo-fb-005", createdAt: daysAgo(3, 15, 10), orderId: "#LME-10444", ticketId: "4782", customerName: "Marcus Webb", customerEmail: "marcus.webb@example.com", country: "AU", theme: "subscription", relatedTeam: "Tech", details: "Found the Hair Edit swap flow confusing — didn't realise swaps close on the 12th. Missed the window this month.", suggestion: "Surface the swap deadline inside the account portal, not only in email.", agent: "demo" },
    { id: "demo-fb-006", createdAt: daysAgo(4, 11, 45), orderId: "#LME-10428", ticketId: "4767", customerName: "Charlotte Ellery", customerEmail: "charlotte.ellery@example.com", country: "GB", theme: "packaging", relatedTeam: "Ops/Logistics", details: "Suggested a pump cover or travel lock — pump got knocked in her gym bag and dispensed into the bag lining.", suggestion: "Pass to packaging review for the next bottle run.", agent: "demo" },
    { id: "demo-fb-007", createdAt: daysAgo(5, 9, 20), orderId: "#LME-10417", ticketId: "4753", customerName: "Priya Nair", customerEmail: "priya.nair@example.com", country: "AU", theme: "shipping", relatedTeam: "Ops/Logistics", details: "Praised the new tracking emails — said the day-before delivery note is the best she's seen from any brand.", agent: "demo" },
    { id: "demo-fb-008", createdAt: daysAgo(6, 16, 35), orderId: "#LME-10404", ticketId: "4737", customerName: "Ethan Rhodes", customerEmail: "ethan.rhodes@example.com", country: "US", theme: "product", relatedTeam: "Product", details: "Asked whether Scalp Serum is safe alongside minoxidil. Playbook answer given (yes, apply at different times of day) — flagged that this question keeps coming up.", suggestion: "Add minoxidil compatibility to the PDP FAQ.", agent: "demo" },
    { id: "demo-fb-009", createdAt: daysAgo(7, 12, 0), orderId: "#LME-10390", ticketId: "4716", customerName: "Casey Kim", customerEmail: "casey.kim@example.com", country: "US", theme: "pricing", relatedTeam: "Marketing", details: "Feels the Hair Edit at $89/month is fair but wishes there were a quarterly plan with a small discount.", suggestion: "Quarterly plan request — recurring theme in cancellation saves too.", agent: "demo" },
    { id: "demo-fb-010", createdAt: daysAgo(13, 10, 25), orderId: "#LME-10349", ticketId: "4660", customerName: "Freya Dunbar", customerEmail: "freya.dunbar@example.com", country: "GB", theme: "service", relatedTeam: "CX", details: "Complimented the agent who handled her delayed box — 'kindest support exchange I've had in years.' Kudos passed to the agent.", agent: "demo" },
    { id: "demo-fb-011", createdAt: daysAgo(22, 14, 15), orderId: "#LME-10290", ticketId: "4577", customerName: "Jack Halloran", customerEmail: "jack.halloran@example.com", country: "AU", theme: "tech", relatedTeam: "Tech", details: "Reported that the hair-profile quiz reset halfway through on mobile Safari. Completed on desktop instead.", suggestion: "Repro steps captured — needs a look from the web team.", agent: "demo" },
  ];
}

// ─── Ops / Order Requests ────────────────────────────────────────────────────
export function orderRequestsSeed() {
  return [
    { id: "demo-or-001", createdAt: hoursAgo(1, 20), region: "AU — Sydney", requestedBy: "Cherie Jones", ticketId: "4828", orderRef: "#LME-10487", referenceNumber: "REQ-2214", omsOrderNumber: "PL-88412", skus: ["LME-SMO-50"], dispatchWarehouse: "SYD-01 (Parcelline)", shipCarrier: "AusPost", awb: "PLAU-83621047", shipDate: dateDaysAgo(0), sent: false, recipientName: "Ruby Tran", shipToCity: "Melbourne", shipToCountry: "AU", itemsDescription: "Smooth Serum x1 — replacement for cracked bottle", status: "pending", notes: "Customer moved — address updated before dispatch.", agent: "demo" },
    { id: "demo-or-002", createdAt: hoursAgo(5, 5), region: "US — Los Angeles", requestedBy: "Cherie Jones", ticketId: "4824", orderRef: "#LME-10484", referenceNumber: "REQ-2213", omsOrderNumber: "PL-88397", skus: ["LME-EDIT-BOX"], dispatchWarehouse: "LAX-02 (Parcelline)", shipCarrier: "USPS", awb: "PLUS-55108236", shipDate: dateDaysAgo(0), sent: false, recipientName: "Skyler Russo", shipToCity: "Austin", shipToCountry: "US", itemsDescription: "Hair Edit box — hold dispatch until June 3, customer travelling", status: "pending", notes: "Dispatch hold requested; release on customer confirmation.", agent: "demo" },
    { id: "demo-or-003", createdAt: daysAgo(1, 11, 35), region: "UK — London", requestedBy: "Cherie Jones", ticketId: "4805", orderRef: "#LME-10465", referenceNumber: "REQ-2209", omsOrderNumber: "PL-88342", skus: ["LME-SCA-30"], dispatchWarehouse: "LHR-01 (Parcelline)", shipCarrier: "Royal Mail", awb: "PLUK-77450912", shipDate: dateDaysAgo(1), sent: true, recipientName: "Charlotte Ellery", shipToCity: "Leeds", shipToCountry: "GB", itemsDescription: "Scalp Serum x1 — express replacement for stalled shipment", status: "shipped", notes: "Original parcel stalled 16 days; replacement sent express.", agent: "demo" },
    { id: "demo-or-004", createdAt: daysAgo(2, 9, 50), region: "AU — Sydney", requestedBy: "Cherie Jones", ticketId: "4789", orderRef: "#LME-10449", referenceNumber: "REQ-2205", omsOrderNumber: "PL-88301", skus: ["LME-REP-50", "LME-GLO-50"], dispatchWarehouse: "SYD-01 (Parcelline)", shipCarrier: "AusPost", awb: "PLAU-83598820", shipDate: dateDaysAgo(2), sent: true, recipientName: "Sophie Brennan", shipToCity: "Sydney", shipToCountry: "AU", itemsDescription: "Repair + Glow Serums — Hair Edit curation fix", status: "delivered", notes: "Fulfilment mismatch corrected; delivered next day.", agent: "demo" },
    { id: "demo-or-005", createdAt: daysAgo(3, 14, 10), region: "US — Los Angeles", requestedBy: "Cherie Jones", ticketId: "4777", orderRef: "#LME-10439", referenceNumber: "REQ-2202", omsOrderNumber: "PL-88275", skus: ["LME-GLO-50"], dispatchWarehouse: "LAX-02 (Parcelline)", shipCarrier: "USPS", awb: "PLUS-55071648", shipDate: dateDaysAgo(3), sent: true, recipientName: "Harper Quinn", shipToCity: "Portland", shipToCountry: "US", itemsDescription: "Glow Serum x1 — misdelivery replacement", status: "delivered", notes: "Courier claim running in parallel — see Parcelline ref.", agent: "demo" },
    { id: "demo-or-006", createdAt: daysAgo(4, 10, 25), region: "UK — London", requestedBy: "Cherie Jones", ticketId: "4762", orderRef: "#LME-10420", referenceNumber: "REQ-2198", omsOrderNumber: "PL-88226", skus: ["LME-EDIT-BOX"], dispatchWarehouse: "LHR-01 (Parcelline)", shipCarrier: "DPD", awb: "PLUK-77412075", shipDate: dateDaysAgo(4), sent: true, recipientName: "Oliver Bennett", shipToCity: "Bristol", shipToCountry: "GB", itemsDescription: "Hair Edit box — re-ship after RTS", status: "delivered", notes: "Address confirmed with customer before re-ship.", agent: "demo" },
    { id: "demo-or-007", createdAt: daysAgo(5, 15, 40), region: "AU — Sydney", requestedBy: "Cherie Jones", ticketId: "4749", orderRef: "#LME-10414", referenceNumber: "REQ-2194", omsOrderNumber: "PL-88190", skus: ["LME-SMO-50", "LME-GLO-50"], dispatchWarehouse: "SYD-01 (Parcelline)", shipCarrier: "AusPost", awb: "PLAU-83570334", shipDate: dateDaysAgo(5), sent: true, recipientName: "Priya Nair", shipToCity: "Brisbane", shipToCountry: "AU", itemsDescription: "Smooth + Glow Serums — gift-ready replacement with handwritten note", status: "delivered", notes: "Gift order — presentation replacement.", agent: "demo" },
    { id: "demo-or-011", createdAt: daysAgo(6, 11, 15), region: "AU — Sydney", requestedBy: "Cherie Jones", ticketId: "4736", orderRef: "#LME-10403", referenceNumber: "REQ-2191", omsOrderNumber: "PL-88168", skus: ["LME-GLO-50"], dispatchWarehouse: "SYD-01 (Parcelline)", shipCarrier: "AusPost", awb: "PLAU-83581122", shipDate: dateDaysAgo(6), sent: true, recipientName: "Liam O'Brien", shipToCity: "Perth", shipToCountry: "AU", itemsDescription: "Glow Serum x1 — goodwill add-on for leaked lid", status: "delivered", notes: "Goodwill approved by Lead.", agent: "demo" },
    { id: "demo-or-008", createdAt: daysAgo(7, 12, 55), region: "US — Los Angeles", requestedBy: "Cherie Jones", ticketId: "4728", orderRef: "#LME-10399", referenceNumber: "REQ-2188", omsOrderNumber: "PL-88144", skus: ["LME-REP-50"], dispatchWarehouse: "LAX-02 (Parcelline)", shipCarrier: "USPS", awb: "PLUS-55039412", shipDate: dateDaysAgo(6), sent: true, recipientName: "Fatima Al-Hassan", shipToCity: "Chicago", shipToCountry: "US", itemsDescription: "Repair Serum x1 — cracked bottle replacement", status: "delivered", notes: "", agent: "demo" },
    { id: "demo-or-009", createdAt: daysAgo(15, 9, 30), region: "UK — London", requestedBy: "Cherie Jones", ticketId: "4645", orderRef: "#LME-10338", referenceNumber: "REQ-2170", omsOrderNumber: "PL-87990", skus: ["LME-SCA-30"], dispatchWarehouse: "LHR-01 (Parcelline)", shipCarrier: "Royal Mail", awb: "PLUK-77355208", shipDate: dateDaysAgo(14), sent: true, recipientName: "Niamh O'Sullivan", shipToCity: "Belfast", shipToCountry: "GB", itemsDescription: "Scalp Serum x1 — shattered bottle replacement, reinforced packaging", status: "delivered", notes: "Carton spec issue flagged to Parcelline.", agent: "demo" },
    { id: "demo-or-010", createdAt: daysAgo(24, 13, 45), region: "AU — Sydney", requestedBy: "Cherie Jones", ticketId: "4538", orderRef: "#LME-10260", referenceNumber: "REQ-2151", omsOrderNumber: "PL-87821", skus: ["LME-EDIT-BOX"], dispatchWarehouse: "SYD-01 (Parcelline)", shipCarrier: "AusPost", awb: "PLAU-83488859", shipDate: dateDaysAgo(23), sent: true, recipientName: "Amelia Cross", shipToCity: "Adelaide", shipToCountry: "AU", itemsDescription: "Hair Edit box — tampered-package replacement", status: "delivered", notes: "Courier chain incident logged with Parcelline Sydney.", agent: "demo" },
  ];
}

// ─── Reaction / Concern (adverse reactions) ──────────────────────────────────
export function adverseReactionsSeed() {
  const base = { patientSameAsCustomer: true, fdaMedwatchFiled: false, mrddNumber: "", returnRequested: false, rmaNumber: "", agent: "demo" };
  return [
    { ...base, id: "demo-ar-001", createdAt: hoursAgo(3, 10), orderId: "#LME-10477", ticketId: "4812", customerName: "Tara Hennessy", customerEmail: "tara.hennessy@example.com", country: "AU", complaintMethod: "email", complaintDescription: "The tingling on my scalp feels like burning — it's really painful, not just a tingle. I had to wash it off immediately.", productsAffected: ["Scalp Serum"], lotNumbers: ["LS-2607-A"], symptoms: ["Burning sensation", "Redness"], severity: "moderate", isSerious: false, escalatedTo: "Head of CX", status: "under-review", agent: "demo" },
    { ...base, id: "demo-ar-002", createdAt: hoursAgo(7, 25), orderId: "#LME-10474", ticketId: "4809", customerName: "Ben Cartwright", customerEmail: "ben.cartwright@example.com", country: "US", complaintMethod: "live-chat", complaintDescription: "Mild itching on my scalp during the first week of Scalp Serum. It settled once I dropped to twice a week.", productsAffected: ["Scalp Serum"], lotNumbers: ["LS-2606-B"], symptoms: ["Itching"], severity: "low", isSerious: false, escalatedTo: "", status: "open", agent: "demo" },
    { ...base, id: "demo-ar-003", createdAt: daysAgo(1, 13, 40), orderId: "#LME-10459", ticketId: "4799", customerName: "Maddison Clarke", customerEmail: "maddison.clarke@example.com", country: "AU", complaintMethod: "email", complaintDescription: "Small red bumps along my hairline two days after starting Glow Serum. No itching, but they're visible.", productsAffected: ["Glow Serum"], lotNumbers: ["LG-2606-C"], symptoms: ["Breakout along hairline", "Redness"], severity: "low", isSerious: false, escalatedTo: "QC Manager", status: "under-review", agent: "demo" },
    { ...base, id: "demo-ar-004", createdAt: daysAgo(2, 10, 15), orderId: "#LME-10446", ticketId: "4786", customerName: "Noah Whitmore", customerEmail: "noah.whitmore@example.com", country: "US", complaintMethod: "instagram", complaintDescription: "My forehead felt tight and looked flushed for about an hour after using Repair Serum near the roots.", productsAffected: ["Repair Serum"], lotNumbers: ["LR-2606-A"], symptoms: ["Redness"], severity: "low", isSerious: false, escalatedTo: "", status: "closed", agent: "demo" },
    { ...base, id: "demo-ar-005", createdAt: daysAgo(3, 15, 50), orderId: "#LME-10436", ticketId: "4773", customerName: "Poppy Ashworth", customerEmail: "poppy.ashworth@example.com", country: "GB", complaintMethod: "email", complaintDescription: "Itchy, flaky patches behind my ears after a week of daily Scalp Serum. Stopped use; it's easing.", productsAffected: ["Scalp Serum"], lotNumbers: ["LS-2606-B"], symptoms: ["Itching", "Flaking / dryness"], severity: "moderate", isSerious: false, escalatedTo: "Head of CX", status: "under-review", agent: "demo" },
    { ...base, id: "demo-ar-006", createdAt: daysAgo(4, 11, 30), orderId: "#LME-10424", ticketId: "4760", customerName: "Harlow James", customerEmail: "harlow.james@example.com", country: "AU", complaintMethod: "phone", complaintDescription: "Hives on my neck the evening after first using Smooth Serum. Antihistamine settled it overnight.", productsAffected: ["Smooth Serum"], lotNumbers: ["LM-2605-D"], symptoms: ["Rash / hives"], severity: "moderate", isSerious: false, escalatedTo: "QC Manager", status: "closed", agent: "demo" },
    { ...base, id: "demo-ar-007", createdAt: daysAgo(5, 14, 5), orderId: "#LME-10413", ticketId: "4746", customerName: "Mia Castellanos", customerEmail: "mia.castellanos@example.com", country: "US", complaintMethod: "email", complaintDescription: "Watery, stinging eyes when Glow Serum mist drifted while spraying. Fine within the hour.", productsAffected: ["Glow Serum"], lotNumbers: ["LG-2605-A"], symptoms: ["Watery eyes"], severity: "low", isSerious: false, escalatedTo: "", status: "closed", agent: "demo" },
    { ...base, id: "demo-ar-008", createdAt: daysAgo(6, 9, 45), orderId: "#LME-10401", ticketId: "4733", customerName: "Freya Dunbar", customerEmail: "freya.dunbar@example.com", country: "GB", complaintMethod: "live-chat", complaintDescription: "Scalp felt warm and prickly for around 20 minutes after applying Scalp Serum — stronger than the usual tingle I was told about.", productsAffected: ["Scalp Serum"], lotNumbers: ["LS-2605-C"], symptoms: ["Burning sensation"], severity: "low", isSerious: false, escalatedTo: "", status: "closed", agent: "demo" },
    { ...base, id: "demo-ar-009", createdAt: daysAgo(7, 16, 20), orderId: "#LME-10391", ticketId: "4717", customerName: "Ethan Rhodes", customerEmail: "ethan.rhodes@example.com", country: "US", complaintMethod: "email", complaintDescription: "Noticeable swelling at my temples the morning after combining Repair and Scalp Serums. Went down within the day.", productsAffected: ["Repair Serum", "Scalp Serum"], lotNumbers: ["LR-2605-B", "LS-2605-C"], symptoms: ["Swelling", "Redness"], severity: "high", isSerious: false, escalatedTo: "Medical Affairs", status: "under-review", agent: "demo" },
    { ...base, id: "demo-ar-010", createdAt: daysAgo(16, 12, 35), orderId: "#LME-10330", ticketId: "4633", customerName: "Isla Mackenzie", customerEmail: "isla.mackenzie@example.com", country: "AU", complaintMethod: "email", complaintDescription: "Dry, tight feeling across the crown after two weeks of daily Smooth Serum. Improved with every-other-day use.", productsAffected: ["Smooth Serum"], lotNumbers: ["LM-2604-A"], symptoms: ["Flaking / dryness"], severity: "low", isSerious: false, escalatedTo: "", status: "closed", agent: "demo" },
  ];
}

// ─── Cancel — No Refund ──────────────────────────────────────────────────────
export function cancelNoRefundSeed() {
  return [
    { id: "demo-cnr-001", createdAt: hoursAgo(2, 30), cancelledOrderId: "#LME-10488", ticketId: "4829", replacementOrderId: "#LME-10489", reasonNotRefunded: "Replacement order shipped instead of refund", notes: "Wrong serum in the Hair Edit box — customer chose a corrected replacement over a refund.", agent: "demo" },
    { id: "demo-cnr-002", createdAt: hoursAgo(6, 40), cancelledOrderId: "#LME-10470", ticketId: "4808", replacementOrderId: "#LME-10490", reasonNotRefunded: "Duplicate order merged into one shipment", notes: "Customer double-ordered by accident; second order cancelled and combined into a single dispatch.", agent: "demo" },
    { id: "demo-cnr-003", createdAt: daysAgo(1, 15, 20), cancelledOrderId: "#LME-10457", ticketId: "4797", replacementOrderId: "#LME-10491", reasonNotRefunded: "Store credit issued at customer's request", notes: "Outside the 30-day window — customer preferred credit toward the next Hair Edit box.", agent: "demo" },
    { id: "demo-cnr-004", createdAt: daysAgo(2, 12, 45), cancelledOrderId: "#LME-10443", ticketId: "4781", replacementOrderId: "#LME-10492", reasonNotRefunded: "Replacement order shipped instead of refund", notes: "Leaked bottle — replacement preferred. Logged for the Parcelline claim.", agent: "demo" },
    { id: "demo-cnr-005", createdAt: daysAgo(3, 10, 10), cancelledOrderId: "#LME-10431", ticketId: "4769", replacementOrderId: "", reasonNotRefunded: "Payment never captured — authorisation released", notes: "Failed payment on renewal; order cancelled before capture, nothing to refund.", agent: "demo" },
    { id: "demo-cnr-006", createdAt: daysAgo(4, 14, 55), cancelledOrderId: "#LME-10418", ticketId: "4754", replacementOrderId: "#LME-10493", reasonNotRefunded: "Exchanged for a different serum at equal value", notes: "Smooth swapped to Repair after a profile update — straight exchange, no money moved.", agent: "demo" },
    { id: "demo-cnr-010", createdAt: daysAgo(5, 16, 5), cancelledOrderId: "#LME-10411", ticketId: "4745", replacementOrderId: "#LME-10495", reasonNotRefunded: "Replacement order shipped instead of refund", notes: "Crushed gift packaging — customer chose the gift-ready replacement over a refund.", agent: "demo" },
    { id: "demo-cnr-007", createdAt: daysAgo(6, 9, 35), cancelledOrderId: "#LME-10400", ticketId: "4731", replacementOrderId: "", reasonNotRefunded: "Outside 30-day window — policy explained", notes: "Refund requested 45 days after purchase. Offered store credit; customer declined, cancellation logged.", agent: "demo" },
    { id: "demo-cnr-008", createdAt: daysAgo(7, 13, 15), cancelledOrderId: "#LME-10389", ticketId: "4712", replacementOrderId: "#LME-10494", reasonNotRefunded: "Replacement order shipped instead of refund", notes: "Lost in transit, confirmed by courier — replacement preferred over refund.", agent: "demo" },
    { id: "demo-cnr-009", createdAt: daysAgo(20, 11, 0), cancelledOrderId: "#LME-10301", ticketId: "4598", replacementOrderId: "", reasonNotRefunded: "Opened product outside the guarantee window", notes: "Two weeks of use then refund request at day 50. Policy does not cover opened product past 30 days.", agent: "demo" },
  ];
}
